/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.Entrada;

import DAO.DetalleEntradaDAO;
import DAO.EntradaDAO;
import DTO.DetalleEntradaTO;
import DTO.EntradaTO;
import GUI.BuscarProductoEntrada;
import GUI.MenuGUI;
import Library.ValidarClass;
import com.sun.glass.events.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEFREY
 */
public class EntradaGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarProductoEntrada
     */
    EntradaDAO objEntradaDAO = new EntradaDAO();
    DetalleEntradaDAO objDetalleEntradaDAO = new DetalleEntradaDAO();
    JRootPane rootPane;
    ResultSet rsTipoPago;
    boolean sw;
    int xidentrada, xidtipopago;
    double precio;
    int cantidad;
    double importe;
    static double subTotal;
    static double total;

    Calendar objfecha_actual = new GregorianCalendar();
    ValidarClass objValidarClass = new ValidarClass();
    DefaultTableModel objDtm;
    SimpleDateFormat objSimpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    public EntradaGUI() {
        initComponents();
        setVisible(true);
        setSize(1058, 632);
        objDtm = (DefaultTableModel) jtblEntrada.getModel();
        jDateFechaActual.setCalendar(objfecha_actual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jlabelprecioCompra = new javax.swing.JLabel();
        jtxtprecioCompra = new javax.swing.JTextField();
        jlabelCantidad = new javax.swing.JLabel();
        jtxtcantidad = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jlabelcodigoProducto = new javax.swing.JLabel();
        jtxtnombreEncargadoEntrada = new javax.swing.JTextField();
        jlabelDescProducto = new javax.swing.JLabel();
        jtxtcodigoEncargadoEntrada = new javax.swing.JTextField();
        btnBuscarEncargado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEntrada = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlabelTotal = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jtxtnombreProveedor = new javax.swing.JTextField();
        jlabelnombreProveedor = new javax.swing.JLabel();
        btnbuscarProveedor = new javax.swing.JButton();
        jlabelnombreProveedor1 = new javax.swing.JLabel();
        jtxtcodigoProveedor = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jlabelnumDocumento1 = new javax.swing.JLabel();
        jtxtnroEntrada = new javax.swing.JTextField();
        jDateFechaActual = new com.toedter.calendar.JDateChooser();
        jlabelnumDocumento2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jlabelcodigoProducto1 = new javax.swing.JLabel();
        jtxtnombreProductoEntrada = new javax.swing.JTextField();
        jlabelDescProducto1 = new javax.swing.JLabel();
        jtxtcodigoProductoEntrada = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jcomboxPago = new javax.swing.JComboBox<>();
        jlabelcodigoProducto2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("AREA DE ENTRADAS");
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jButton1))
                .addGap(5, 5, 5))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlabelprecioCompra.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelprecioCompra.setText("P.COMPRA:");

        jtxtprecioCompra.setEditable(false);
        jtxtprecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtprecioCompraActionPerformed(evt);
            }
        });
        jtxtprecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtprecioCompraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtprecioCompraKeyTyped(evt);
            }
        });

        jlabelCantidad.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelCantidad.setText("CANTIDAD:");

        jtxtcantidad.setEditable(false);
        jtxtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcantidadActionPerformed(evt);
            }
        });
        jtxtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcantidadKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlabelprecioCompra)
                .addGap(10, 10, 10)
                .addComponent(jtxtprecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jlabelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelprecioCompra)
                    .addComponent(jtxtprecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelCantidad))
                .addGap(5, 5, 5))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlabelcodigoProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelcodigoProducto.setText("CODIGO:");

        jtxtnombreEncargadoEntrada.setEditable(false);
        jtxtnombreEncargadoEntrada.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreEncargadoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreEncargadoEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreEncargadoEntradaKeyTyped(evt);
            }
        });

        jlabelDescProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelDescProducto.setText("DESCRIPCION ENCARGADO:");

        jtxtcodigoEncargadoEntrada.setEditable(false);
        jtxtcodigoEncargadoEntrada.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoEncargadoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoEncargadoEntradaActionPerformed(evt);
            }
        });
        jtxtcodigoEncargadoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoEncargadoEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoEncargadoEntradaKeyTyped(evt);
            }
        });

        btnBuscarEncargado.setText("BUSCAR");
        btnBuscarEncargado.setEnabled(false);
        btnBuscarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEncargadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtnombreEncargadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelDescProducto)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcodigoEncargadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelcodigoProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarEncargado)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlabelcodigoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoEncargadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelDescProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnombreEncargadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jtblEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "DESCRIPCION", "PCOMPRA", "CANTIDAD", "SUB TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblEntrada);
        if (jtblEntrada.getColumnModel().getColumnCount() > 0) {
            jtblEntrada.getColumnModel().getColumn(0).setMinWidth(70);
            jtblEntrada.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtblEntrada.getColumnModel().getColumn(0).setMaxWidth(70);
            jtblEntrada.getColumnModel().getColumn(1).setMinWidth(300);
            jtblEntrada.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtblEntrada.getColumnModel().getColumn(1).setMaxWidth(300);
            jtblEntrada.getColumnModel().getColumn(2).setResizable(false);
            jtblEntrada.getColumnModel().getColumn(3).setResizable(false);
            jtblEntrada.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nuevo.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminarProducto.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/deleteproducto.png"))); // NOI18N
        btnEliminarProducto.setEnabled(false);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar))))
                .addGap(5, 5, 5))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlabelTotal.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal.setText("TOTAL S/.");

        jtxtTotal.setEditable(false);
        jtxtTotal.setBackground(new java.awt.Color(255, 255, 153));
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jtxtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTotalKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtxtnombreProveedor.setEditable(false);
        jtxtnombreProveedor.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreProveedorActionPerformed(evt);
            }
        });
        jtxtnombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreProveedorKeyTyped(evt);
            }
        });

        jlabelnombreProveedor.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor.setText("CODIGO:");

        btnbuscarProveedor.setText("BUSCAR");
        btnbuscarProveedor.setEnabled(false);
        btnbuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarProveedorActionPerformed(evt);
            }
        });

        jlabelnombreProveedor1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor1.setText("DESCRIPCION PROVEEDOR:");

        jtxtcodigoProveedor.setEditable(false);
        jtxtcodigoProveedor.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoProveedorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelnombreProveedor))
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscarProveedor))
                    .addComponent(jtxtnombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelnombreProveedor1))
                .addGap(10, 10, 10))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlabelnombreProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelnombreProveedor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlabelnumDocumento1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnumDocumento1.setText("NºDOCUMENTO:");

        jtxtnroEntrada.setEditable(false);
        jtxtnroEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnroEntradaActionPerformed(evt);
            }
        });
        jtxtnroEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnroEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnroEntradaKeyTyped(evt);
            }
        });

        jDateFechaActual.setDateFormatString("dd/MM/yyyy HH:mm:ss");

        jlabelnumDocumento2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnumDocumento2.setText("FECHA REGISTRO:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelnumDocumento1)
                    .addComponent(jtxtnroEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jlabelnumDocumento2)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jDateFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelnumDocumento1)
                    .addComponent(jlabelnumDocumento2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateFechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jtxtnroEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlabelcodigoProducto1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelcodigoProducto1.setText("CODIGO:");

        jtxtnombreProductoEntrada.setEditable(false);
        jtxtnombreProductoEntrada.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreProductoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreProductoEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreProductoEntradaKeyTyped(evt);
            }
        });

        jlabelDescProducto1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelDescProducto1.setText("DESCRIPCION PRODUCTO:");

        jtxtcodigoProductoEntrada.setEditable(false);
        jtxtcodigoProductoEntrada.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoProductoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoProductoEntradaActionPerformed(evt);
            }
        });
        jtxtcodigoProductoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoProductoEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoProductoEntradaKeyTyped(evt);
            }
        });

        btnBuscarProducto.setText("BUSCAR");
        btnBuscarProducto.setEnabled(false);
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jcomboxPago.setEnabled(false);

        jlabelcodigoProducto2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelcodigoProducto2.setText("UNIDAD DE MEDIDA:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtnombreProductoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelDescProducto1)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcodigoProductoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelcodigoProducto1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarProducto)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcomboxPago, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelcodigoProducto2))))
                .addGap(10, 10, 10))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelcodigoProducto1)
                    .addComponent(jlabelcodigoProducto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoProductoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboxPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelDescProducto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnombreProductoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnombreEncargadoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoEntradaKeyTyped

    private void jtxtnombreEncargadoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoEntradaKeyReleased

    private void jtxtcodigoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProveedorKeyTyped

    private void jtxtcodigoProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProveedorKeyReleased

    private void jtxtnombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorKeyTyped

    private void jtxtnombreProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorKeyReleased

    private void jtxtcodigoEncargadoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoEntradaKeyReleased

    private void jtxtcodigoEncargadoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoEntradaKeyTyped

    private void jtxtprecioCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtprecioCompraKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            jtxtcantidad.grabFocus();
        }
    }//GEN-LAST:event_jtxtprecioCompraKeyReleased

    private void jtxtprecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtprecioCompraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtprecioCompraKeyTyped

    private void jtxtnombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorActionPerformed

    private void jtxtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalKeyReleased

    private void jtxtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalKeyTyped

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        objDtm.removeRow((jtblEntrada.getSelectedRow()));
        calcularTotales();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            /*ENTRADA*/
            EntradaTO objEntradaTO = new EntradaTO();
            String fecha = objSimpleDateFormat.format(jDateFechaActual.getDate());
            objEntradaTO.setFechaent(fecha);
            objEntradaTO.setNroent(jtxtnroEntrada.getText().toUpperCase().trim());
            objEntradaTO.setIdtipago(xidtipopago);
            objEntradaTO.setIdencargado(Integer.parseInt(jtxtcodigoEncargadoEntrada.getText()));
            objEntradaTO.setIdproveedor(Integer.parseInt(jtxtcodigoProveedor.getText()));
            objEntradaTO.setTotalent(total);
            objEntradaDAO.insert(objEntradaTO);
            xidentrada = objEntradaDAO.obternerIDIngreso();
            /*DETALLE-ENTRADA*/
            int filas = objDtm.getRowCount();
            for (int i = 0; i < filas; i++) {
                DetalleEntradaTO objDetalleEntradaTO = new DetalleEntradaTO();
                objDetalleEntradaTO.setIdentrada(xidentrada);
                objDetalleEntradaTO.setIdproducto(Integer.parseInt(jtblEntrada.getValueAt(i, 0).toString()));
                objDetalleEntradaTO.setPcompraent(Double.parseDouble(jtblEntrada.getValueAt(i, 2).toString()));
                objDetalleEntradaTO.setCantidadent(Integer.parseInt(jtblEntrada.getValueAt(i, 3).toString()));
                objDetalleEntradaTO.setImporteent(Double.parseDouble(jtblEntrada.getValueAt(i, 4).toString()));
                objDetalleEntradaDAO.insert(objDetalleEntradaTO);
            }
            habilitarControles(false);
            JOptionPane.showMessageDialog(rootPane, "ENTRADA GRABADO");
            limpiarControles();
            jcomboxPago.removeAllItems();
            jDateFechaActual.setCalendar(objfecha_actual);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnbuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarProveedorActionPerformed
        BuscarProveedorEntrada objBuscarProveedorGUI = new BuscarProveedorEntrada();
        MenuGUI.desktopPane.add(objBuscarProveedorGUI);
        objBuscarProveedorGUI.setVisible(true);
        objBuscarProveedorGUI.setLocation(500, 150);
        objBuscarProveedorGUI.setSize(510, 320);
        objBuscarProveedorGUI.toFront();
    }//GEN-LAST:event_btnbuscarProveedorActionPerformed

    private void btnBuscarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEncargadoActionPerformed
        BuscarEncargadoEntrada objBuscarEncargadoGUI = new BuscarEncargadoEntrada();
        MenuGUI.desktopPane.add(objBuscarEncargadoGUI);
        objBuscarEncargadoGUI.setVisible(true);
        objBuscarEncargadoGUI.setLocation(500, 150);
        objBuscarEncargadoGUI.setSize(490, 320);
        objBuscarEncargadoGUI.toFront();
    }//GEN-LAST:event_btnBuscarEncargadoActionPerformed

    public void agregarProducto() {
        if (importe == 0) {
            JOptionPane.showMessageDialog(rootPane, "REGISTRAR LOS PRODUCTOS");
        } else {
            sw = false;
            int cont = 0;
            int idproducto = Integer.parseInt(jtxtcodigoProductoEntrada.getText());
            Object registro[] = {jtxtcodigoProductoEntrada.getText(), jtxtnombreProductoEntrada.getText(), precio,
                cantidad, importe};
            if (objDtm.getRowCount() == 0) {
                objDtm.addRow(registro);
                limpiarProducto();
            } else {
                while (cont < objDtm.getRowCount()) {
                    if (idproducto == Integer.parseInt(objDtm.getValueAt(cont, 0).toString())) {
                        JOptionPane.showMessageDialog(rootPane, "REGISTRO YA EXISTE");
                        sw = true;
                    }
                    cont++;
                }
                if (!sw) {
                    objDtm.addRow(registro);
                }
            }
            limpiarProducto();
        }
        calcularTotales();
    }
    private void jtxtcodigoEncargadoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoEntradaActionPerformed

    private void jtxtprecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtprecioCompraActionPerformed

    }//GEN-LAST:event_jtxtprecioCompraActionPerformed

    private void jtxtnroEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnroEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnroEntradaKeyReleased

    private void jtxtnroEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnroEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnroEntradaKeyTyped

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtnroEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnroEntradaActionPerformed

    }//GEN-LAST:event_jtxtnroEntradaActionPerformed

    private void jtxtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcantidadActionPerformed
        precio = Double.parseDouble(jtxtprecioCompra.getText().trim());
        cantidad = Integer.parseInt(jtxtcantidad.getText().trim());
        importe = precio * cantidad;
    }//GEN-LAST:event_jtxtcantidadActionPerformed

    private void jtxtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcantidadKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            agregarProducto();
        }
    }//GEN-LAST:event_jtxtcantidadKeyReleased

    private void jtxtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcantidadKeyTyped
        objValidarClass.numberKeyPress(evt);
    }//GEN-LAST:event_jtxtcantidadKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
        jcomboxPago.removeAllItems();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitarControles(true);
        limpiarControles();
        sw = true;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jtxtnombreProductoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProductoEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProductoEntradaKeyReleased

    private void jtxtnombreProductoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProductoEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProductoEntradaKeyTyped

    private void jtxtcodigoProductoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoEntradaActionPerformed

    private void jtxtcodigoProductoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoEntradaKeyReleased

    private void jtxtcodigoProductoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoEntradaKeyTyped

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        BuscarProductoEntrada objBuscarProductoGUI = new BuscarProductoEntrada();
        MenuGUI.desktopPane.add(objBuscarProductoGUI);
        objBuscarProductoGUI.setVisible(true);
        objBuscarProductoGUI.setLocation(500, 150);
        objBuscarProductoGUI.setSize(490, 315);
        objBuscarProductoGUI.toFront();
    }//GEN-LAST:event_btnBuscarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEncargado;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnbuscarProveedor;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateFechaActual;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcomboxPago;
    private javax.swing.JLabel jlabelCantidad;
    private javax.swing.JLabel jlabelDescProducto;
    private javax.swing.JLabel jlabelDescProducto1;
    private javax.swing.JLabel jlabelTotal;
    private javax.swing.JLabel jlabelcodigoProducto;
    private javax.swing.JLabel jlabelcodigoProducto1;
    private javax.swing.JLabel jlabelcodigoProducto2;
    private javax.swing.JLabel jlabelnombreProveedor;
    private javax.swing.JLabel jlabelnombreProveedor1;
    private javax.swing.JLabel jlabelnumDocumento1;
    private javax.swing.JLabel jlabelnumDocumento2;
    private javax.swing.JLabel jlabelprecioCompra;
    private javax.swing.JTable jtblEntrada;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtcantidad;
    public static javax.swing.JTextField jtxtcodigoEncargadoEntrada;
    public static javax.swing.JTextField jtxtcodigoProductoEntrada;
    public static javax.swing.JTextField jtxtcodigoProveedor;
    public static javax.swing.JTextField jtxtnombreEncargadoEntrada;
    public static javax.swing.JTextField jtxtnombreProductoEntrada;
    public static javax.swing.JTextField jtxtnombreProveedor;
    private javax.swing.JTextField jtxtnroEntrada;
    public static javax.swing.JTextField jtxtprecioCompra;
    // End of variables declaration//GEN-END:variables

    private void habilitarControles(boolean b) {
        JTextField[] arrJTexFields = {jtxtnroEntrada,
            jtxtprecioCompra, jtxtcantidad};
        for (JTextField obJTextField : arrJTexFields) {
            obJTextField.setEditable(b);
        }

        jtxtnroEntrada.grabFocus();
        btnGuardar.setEnabled(b);
        btnCancelar.setEnabled(b);
        btnNuevo.setEnabled(!b);
        btnEliminarProducto.setEnabled(b);
        btnbuscarProveedor.setEnabled(b);
        btnBuscarEncargado.setEnabled(b);
        btnBuscarProducto.setEnabled(b);
        jcomboxPago.setEnabled(b);
        btnEliminarProducto.setEnabled(b);
    }

    private void limpiarControles() {
        limpiarJTable();
        JTextField[] objTextFields = {jtxtnroEntrada, jtxtcodigoProveedor, jtxtnombreProveedor, jtxtcodigoEncargadoEntrada,
            jtxtnombreEncargadoEntrada, jtxtcodigoProductoEntrada, jtxtnombreProductoEntrada, jtxtprecioCompra, jtxtcantidad, jtxtTotal};
        for (JTextField objTextField : objTextFields) {
            objTextField.setText(null);
        }

    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }

    private void calcularTotales() {
        subTotal = 0;
        total = 0;
        int filas = objDtm.getRowCount();
        int cont = 0;
        while (cont < filas) {
            total = total + Double.parseDouble(objDtm.getValueAt(cont, 4).toString());
            cont++;
        }
        jtxtTotal.setText(String.format("%.2f", total));
    }

    private void limpiarProducto() {
        jtxtcodigoProductoEntrada.setText(null);
        jtxtnombreProductoEntrada.setText(null);
        jtxtprecioCompra.setText(null);
        jtxtcantidad.setText(null);
        cantidad = 0;
        precio = 0;
        importe = 0;
    }

}
