/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.Entrada;

import DAO.DetalleEntradaDAO;
import DAO.EntradaDAO;
import DAO.PrePrecioDAO;
import DAO.PresentacionDAO;
import DTO.DetalleEntradaTO;
import DTO.EntradaTO;
import GUI.MenuGUI;
import Library.ValidarClass;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEFREY
 */
public class EntradaGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarProductoEntrada
     */
    EntradaDAO objEntradaDAO = new EntradaDAO();
    EntradaTO objEntradaTO = new EntradaTO();
    PresentacionDAO objPresentacionDAO = new PresentacionDAO();
    PrePrecioDAO objPrePrecioDAO = new PrePrecioDAO();
    DetalleEntradaDAO objDetalleEntradaDAO = new DetalleEntradaDAO();
    JRootPane rootPane;
    ButtonGroup objButtonGroup = new ButtonGroup();
    ResultSet rspresentacion;
    boolean sw;
    int xidentrada, xidtipopago;
    double precio;
    int cantidad;
    String op;
    double importe;
    static double subTotal;
    static double total;
    Calendar objfecha_actual = new GregorianCalendar();
    ValidarClass objValidarClass = new ValidarClass();
    DefaultTableModel objDtm;
    SimpleDateFormat objSimpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String mensaje;

    public EntradaGUI() {
        initComponents();
        setVisible(true);
        setSize(1068, 578);
        this.getContentPane().setBackground(Color.white);
        objDtm = (DefaultTableModel) jtblEntrada.getModel();
        jDateFechaRegistro.setCalendar(objfecha_actual);
        objButtonGroup.add(jradContado);
        objButtonGroup.add(jradCredito);

    }

    private void generarSerie() {
        try {
            String serie = objEntradaDAO.nroSerieEntrada();
            if (serie == null) {
                jtxtnroEntrada.setText("001-1");
            } else {
                int incremento = Integer.parseInt(serie);
                incremento++;
                jtxtnroEntrada.setText("001-" + incremento);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jlabelcodigoProducto = new javax.swing.JLabel();
        jtxtnombreEncargadoEntrada = new javax.swing.JTextField();
        jlabelDescProducto = new javax.swing.JLabel();
        jtxtcodigoEncargadoEntrada = new javax.swing.JTextField();
        btnBuscarEncargado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEntrada = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlabelTotal = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jlabelTotal1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jtxtnombreProveedor = new javax.swing.JTextField();
        jlabelnombreProveedor = new javax.swing.JLabel();
        btnbuscarProveedor = new javax.swing.JButton();
        jlabelnombreProveedor1 = new javax.swing.JLabel();
        jtxtcodigoProveedor = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jlabeNroDocumento = new javax.swing.JLabel();
        jtxtnroEntrada = new javax.swing.JTextField();
        jDateFechaRegistro = new com.toedter.calendar.JDateChooser();
        jlabelFechaRegistro = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jlabelcodigoProducto1 = new javax.swing.JLabel();
        jtxtDescrProducto = new javax.swing.JTextField();
        jlabelDescProducto1 = new javax.swing.JLabel();
        jtxtcodigoProductoEntrada = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jlabelprecioCompra = new javax.swing.JLabel();
        jtxtprecioVenta = new javax.swing.JTextField();
        jlabelCantidad = new javax.swing.JLabel();
        jtxtcantidad = new javax.swing.JTextField();
        jcomboxPresentacion = new javax.swing.JComboBox<>();
        jlabelDescProducto2 = new javax.swing.JLabel();
        jlabelDescProducto3 = new javax.swing.JLabel();
        jcomboxUnidadMedida = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jlabelTipoPago = new javax.swing.JLabel();
        jradContado = new javax.swing.JRadioButton();
        jradCredito = new javax.swing.JRadioButton();
        btnEliminarProducto = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("AREA DE ENTRADAS");
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabelTitulo)
                .addGap(9, 9, 9))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setOpaque(false);

        jlabelcodigoProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelcodigoProducto.setText("CODIGO:");

        jtxtnombreEncargadoEntrada.setEditable(false);
        jtxtnombreEncargadoEntrada.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreEncargadoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreEncargadoEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreEncargadoEntradaKeyTyped(evt);
            }
        });

        jlabelDescProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelDescProducto.setText("DESCRIPCION ENCARGADO:");

        jtxtcodigoEncargadoEntrada.setEditable(false);
        jtxtcodigoEncargadoEntrada.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoEncargadoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoEncargadoEntradaActionPerformed(evt);
            }
        });
        jtxtcodigoEncargadoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoEncargadoEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoEncargadoEntradaKeyTyped(evt);
            }
        });

        btnBuscarEncargado.setText("BUSCAR");
        btnBuscarEncargado.setEnabled(false);
        btnBuscarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEncargadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtnombreEncargadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelDescProducto)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcodigoEncargadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelcodigoProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarEncargado)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlabelcodigoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoEncargadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelDescProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnombreEncargadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jtblEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "DESCRIPCION", "PCOMPRA", "CANTIDAD", "SUB TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblEntrada);
        if (jtblEntrada.getColumnModel().getColumnCount() > 0) {
            jtblEntrada.getColumnModel().getColumn(0).setMinWidth(70);
            jtblEntrada.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtblEntrada.getColumnModel().getColumn(0).setMaxWidth(70);
            jtblEntrada.getColumnModel().getColumn(1).setMinWidth(300);
            jtblEntrada.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtblEntrada.getColumnModel().getColumn(1).setMaxWidth(300);
            jtblEntrada.getColumnModel().getColumn(2).setResizable(false);
            jtblEntrada.getColumnModel().getColumn(3).setResizable(false);
            jtblEntrada.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setOpaque(false);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nuevo.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salida.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);

        jlabelTotal.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal.setText("MONTO TOTAL:");

        jtxtTotal.setEditable(false);
        jtxtTotal.setBackground(new java.awt.Color(255, 255, 153));
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jtxtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTotalKeyTyped(evt);
            }
        });

        jlabelTotal1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal1.setText("S/.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelTotal)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlabelTotal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jlabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setOpaque(false);

        jtxtnombreProveedor.setEditable(false);
        jtxtnombreProveedor.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreProveedorActionPerformed(evt);
            }
        });
        jtxtnombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreProveedorKeyTyped(evt);
            }
        });

        jlabelnombreProveedor.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor.setText("CODIGO:");

        btnbuscarProveedor.setText("BUSCAR");
        btnbuscarProveedor.setEnabled(false);
        btnbuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarProveedorActionPerformed(evt);
            }
        });

        jlabelnombreProveedor1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor1.setText("DESCRIPCION PROVEEDOR:");

        jtxtcodigoProveedor.setEditable(false);
        jtxtcodigoProveedor.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoProveedorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelnombreProveedor))
                        .addGap(10, 10, 10)
                        .addComponent(btnbuscarProveedor))
                    .addComponent(jtxtnombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelnombreProveedor1))
                .addGap(10, 10, 10))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlabelnombreProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelnombreProveedor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setOpaque(false);

        jlabeNroDocumento.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabeNroDocumento.setText("NºDOCUMENTO:");

        jtxtnroEntrada.setEditable(false);
        jtxtnroEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnroEntradaActionPerformed(evt);
            }
        });
        jtxtnroEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnroEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnroEntradaKeyTyped(evt);
            }
        });

        jDateFechaRegistro.setDateFormatString("dd/MM/yyyy HH:mm:ss");
        jDateFechaRegistro.setOpaque(false);

        jlabelFechaRegistro.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelFechaRegistro.setText("FECHA REGISTRO:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabeNroDocumento)
                    .addComponent(jtxtnroEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jlabelFechaRegistro)
                        .addGap(87, 116, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jDateFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabeNroDocumento)
                    .addComponent(jlabelFechaRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jtxtnroEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setOpaque(false);

        jlabelcodigoProducto1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelcodigoProducto1.setText("CODIGO:");

        jtxtDescrProducto.setEditable(false);
        jtxtDescrProducto.setBackground(new java.awt.Color(204, 204, 204));
        jtxtDescrProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtDescrProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDescrProductoKeyTyped(evt);
            }
        });

        jlabelDescProducto1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelDescProducto1.setText("DESCRIPCION PRODUCTO:");

        jtxtcodigoProductoEntrada.setEditable(false);
        jtxtcodigoProductoEntrada.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoProductoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoProductoEntradaActionPerformed(evt);
            }
        });
        jtxtcodigoProductoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoProductoEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoProductoEntradaKeyTyped(evt);
            }
        });

        btnBuscarProducto.setText("BUSCAR");
        btnBuscarProducto.setEnabled(false);
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jlabelprecioCompra.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelprecioCompra.setText("PRECIO:");

        jtxtprecioVenta.setEditable(false);
        jtxtprecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtprecioVentaActionPerformed(evt);
            }
        });
        jtxtprecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtprecioVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtprecioVentaKeyTyped(evt);
            }
        });

        jlabelCantidad.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelCantidad.setText("CANTIDAD:");

        jtxtcantidad.setEditable(false);
        jtxtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcantidadActionPerformed(evt);
            }
        });
        jtxtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcantidadKeyTyped(evt);
            }
        });

        jcomboxPresentacion.setEnabled(false);
        jcomboxPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboxPresentacionActionPerformed(evt);
            }
        });
        jcomboxPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcomboxPresentacionKeyReleased(evt);
            }
        });

        jlabelDescProducto2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelDescProducto2.setText("UNIDAD MEDIDA:");

        jlabelDescProducto3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelDescProducto3.setText("PRESENTACION:");

        jcomboxUnidadMedida.setEnabled(false);
        jcomboxUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboxUnidadMedidaActionPerformed(evt);
            }
        });
        jcomboxUnidadMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcomboxUnidadMedidaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlabelcodigoProducto1)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jtxtcodigoProductoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBuscarProducto)))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcomboxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlabelDescProducto2)))
                        .addComponent(jtxtDescrProducto))
                    .addComponent(jlabelDescProducto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelDescProducto3)
                    .addComponent(jcomboxPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtprecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelprecioCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelCantidad)
                            .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelcodigoProducto1)
                    .addComponent(jlabelDescProducto2)
                    .addComponent(jlabelDescProducto3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoProductoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboxPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelDescProducto1)
                    .addComponent(jlabelprecioCompra)
                    .addComponent(jlabelCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDescrProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtprecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setOpaque(false);

        jlabelTipoPago.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTipoPago.setText("TIPO DE PAGO:");

        jradContado.setText("CONTADO");
        jradContado.setEnabled(false);

        jradCredito.setText("CREDITO");
        jradCredito.setEnabled(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlabelTipoPago)
                .addGap(64, 64, 64)
                .addComponent(jradContado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jradCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelTipoPago)
                    .addComponent(jradContado)
                    .addComponent(jradCredito))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminarProducto.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/deleteproducto.png"))); // NOI18N
        btnEliminarProducto.setEnabled(false);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnombreEncargadoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoEntradaKeyTyped

    private void jtxtnombreEncargadoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoEntradaKeyReleased

    private void jtxtcodigoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProveedorKeyTyped

    private void jtxtcodigoProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProveedorKeyReleased

    private void jtxtnombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorKeyTyped

    private void jtxtnombreProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorKeyReleased

    private void jtxtcodigoEncargadoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoEntradaKeyReleased

    private void jtxtcodigoEncargadoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoEntradaKeyTyped

    private void jtxtprecioVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtprecioVentaKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            jtxtcantidad.grabFocus();
        }
    }//GEN-LAST:event_jtxtprecioVentaKeyReleased

    private void jtxtprecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtprecioVentaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtprecioVentaKeyTyped

    private void jtxtnombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorActionPerformed

    private void jtxtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalKeyReleased

    private void jtxtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalKeyTyped

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        objDtm.removeRow((jtblEntrada.getSelectedRow()));
        calcularTotales();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (jtxtcodigoEncargadoEntrada.getText().trim().length() == 0
                    || jtxtcodigoProveedor.getText().trim().length() == 0
                    || this.jtblEntrada.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "COMPLETAR CAJA DE TEXTO", "FERRETERIA MICKY", JOptionPane.WARNING_MESSAGE);
            } else {
                /*ENTRADA*/
                String fecha = objSimpleDateFormat.format(jDateFechaRegistro.getDate());
                objEntradaTO.setFechaent(fecha);
                objEntradaTO.setNroent(jtxtnroEntrada.getText().toUpperCase().trim());
                jcheckSelecionar();
                objEntradaTO.setTipopago(op);
                objEntradaTO.setIdencargado(Integer.parseInt(jtxtcodigoEncargadoEntrada.getText()));
                objEntradaTO.setIdproveedor(Integer.parseInt(jtxtcodigoProveedor.getText()));
                objEntradaTO.setTotalent(total);
                objEntradaDAO.insert(objEntradaTO);
                xidentrada = objEntradaDAO.obternerIDIngreso();
                /*DETALLE-ENTRADA*/
                int filas = objDtm.getRowCount();
                for (int i = 0; i < filas; i++) {
                    DetalleEntradaTO objDetalleEntradaTO = new DetalleEntradaTO();
                    objDetalleEntradaTO.setIdentrada(xidentrada);
                    objDetalleEntradaTO.setIdproducto(Integer.parseInt(jtblEntrada.getValueAt(i, 0).toString()));
                    objDetalleEntradaTO.setPcompraent(Double.parseDouble(jtblEntrada.getValueAt(i, 2).toString()));
                    objDetalleEntradaTO.setCantidadent(Integer.parseInt(jtblEntrada.getValueAt(i, 3).toString()));
                    objDetalleEntradaTO.setImporteent(Double.parseDouble(jtblEntrada.getValueAt(i, 4).toString()));
                    objDetalleEntradaDAO.insert(objDetalleEntradaTO);
                }

                habilitarControles(false);
                mensaje = "ENTRADA GUARDADO";
                JOptionPane.showMessageDialog(null, mensaje, "FERRETERIA MICKY", JOptionPane.INFORMATION_MESSAGE);
                limpiarControles();
                jDateFechaRegistro.setCalendar(objfecha_actual);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "FERRETERIA MICKY", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnbuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarProveedorActionPerformed
        BPV_EntradaGUI objBPV_EntradaGUI = new BPV_EntradaGUI();
        MenuGUI.desktopPane.add(objBPV_EntradaGUI);
        objBPV_EntradaGUI.setVisible(true);
        objBPV_EntradaGUI.setLocation(500, 150);
        objBPV_EntradaGUI.setSize(560, 326);
        objBPV_EntradaGUI.toFront();
    }//GEN-LAST:event_btnbuscarProveedorActionPerformed

    private void btnBuscarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEncargadoActionPerformed
        BE_EntradaGUI objBE_EntradaGUI = new BE_EntradaGUI();
        MenuGUI.desktopPane.add(objBE_EntradaGUI);
        objBE_EntradaGUI.setVisible(true);
        objBE_EntradaGUI.setLocation(500, 150);
        objBE_EntradaGUI.setSize(560, 326);
        objBE_EntradaGUI.toFront();
    }//GEN-LAST:event_btnBuscarEncargadoActionPerformed

    public void agregarProducto() {
        if (importe == 0) {
            JOptionPane.showMessageDialog(rootPane, "REGISTRAR LOS PRODUCTOS");
        } else {
            sw = false;
            int cont = 0;
            int idproducto = Integer.parseInt(jtxtcodigoProductoEntrada.getText());
            Object registro[] = {jtxtcodigoProductoEntrada.getText(), jtxtDescrProducto.getText(), precio,
                cantidad, importe};
            if (objDtm.getRowCount() == 0) {
                objDtm.addRow(registro);
                limpiarProducto();
            } else {
                while (cont < objDtm.getRowCount()) {
                    if (idproducto == Integer.parseInt(objDtm.getValueAt(cont, 0).toString())) {
                        JOptionPane.showMessageDialog(rootPane, "REGISTRO YA EXISTE");
                        sw = true;
                    }
                    cont++;
                }
                if (!sw) {
                    objDtm.addRow(registro);
                }
            }
            limpiarProducto();
        }
        calcularTotales();
    }
    private void jtxtcodigoEncargadoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoEntradaActionPerformed

    private void jtxtprecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtprecioVentaActionPerformed

    }//GEN-LAST:event_jtxtprecioVentaActionPerformed

    private void jtxtnroEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnroEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnroEntradaKeyReleased

    private void jtxtnroEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnroEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnroEntradaKeyTyped

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtnroEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnroEntradaActionPerformed

    }//GEN-LAST:event_jtxtnroEntradaActionPerformed

    private void jtxtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcantidadActionPerformed
        precio = Double.parseDouble(jtxtprecioVenta.getText().trim());
        cantidad = Integer.parseInt(jtxtcantidad.getText().trim());
        importe = precio * cantidad;
    }//GEN-LAST:event_jtxtcantidadActionPerformed

    private void jtxtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcantidadKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            agregarProducto();
        }
    }//GEN-LAST:event_jtxtcantidadKeyReleased

    private void jtxtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcantidadKeyTyped
        objValidarClass.numberKeyPress(evt);
    }//GEN-LAST:event_jtxtcantidadKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
        objButtonGroup.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitarControles(true);
        limpiarControles();
        sw = true;
        generarSerie();
        jradContado.setSelected(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jtxtDescrProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDescrProductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDescrProductoKeyReleased

    private void jtxtDescrProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDescrProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDescrProductoKeyTyped

    private void jtxtcodigoProductoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoEntradaActionPerformed

    private void jtxtcodigoProductoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoEntradaKeyReleased

    private void jtxtcodigoProductoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoEntradaKeyTyped

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        BP_EntradaGUI objBP_EntradaGUI = new BP_EntradaGUI();
        MenuGUI.desktopPane.add(objBP_EntradaGUI);
        objBP_EntradaGUI.setVisible(true);
        objBP_EntradaGUI.setLocation(500, 150);
        objBP_EntradaGUI.setSize(600, 325);
        objBP_EntradaGUI.toFront();
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void jcomboxPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboxPresentacionActionPerformed
        try {
            String dataPresent = String.valueOf(jcomboxPresentacion.getSelectedItem());
            String idproducto = jtxtcodigoProductoEntrada.getText();
            double xprecio = objEntradaDAO.obtenerPrecioPresent(dataPresent, idproducto);
            jtxtprecioVenta.setText(String.format("%.2f", xprecio));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jcomboxPresentacionActionPerformed

    private void jcomboxPresentacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboxPresentacionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboxPresentacionKeyReleased

    private void jcomboxUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboxUnidadMedidaActionPerformed
        llenarComboUDM();
        jcomboxPresentacion.setEnabled(true);
    }//GEN-LAST:event_jcomboxUnidadMedidaActionPerformed

    private void jcomboxUnidadMedidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboxUnidadMedidaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboxUnidadMedidaKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEncargado;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnbuscarProveedor;
    private com.toedter.calendar.JDateChooser jDateFechaRegistro;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<String> jcomboxPresentacion;
    public static javax.swing.JComboBox<String> jcomboxUnidadMedida;
    private javax.swing.JLabel jlabeNroDocumento;
    private javax.swing.JLabel jlabelCantidad;
    private javax.swing.JLabel jlabelDescProducto;
    private javax.swing.JLabel jlabelDescProducto1;
    private javax.swing.JLabel jlabelDescProducto2;
    private javax.swing.JLabel jlabelDescProducto3;
    private javax.swing.JLabel jlabelFechaRegistro;
    private javax.swing.JLabel jlabelTipoPago;
    private javax.swing.JLabel jlabelTotal;
    private javax.swing.JLabel jlabelTotal1;
    private javax.swing.JLabel jlabelcodigoProducto;
    private javax.swing.JLabel jlabelcodigoProducto1;
    private javax.swing.JLabel jlabelnombreProveedor;
    private javax.swing.JLabel jlabelnombreProveedor1;
    private javax.swing.JLabel jlabelprecioCompra;
    private javax.swing.JRadioButton jradContado;
    private javax.swing.JRadioButton jradCredito;
    private javax.swing.JTable jtblEntrada;
    public static javax.swing.JTextField jtxtDescrProducto;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtcantidad;
    public static javax.swing.JTextField jtxtcodigoEncargadoEntrada;
    public static javax.swing.JTextField jtxtcodigoProductoEntrada;
    public static javax.swing.JTextField jtxtcodigoProveedor;
    public static javax.swing.JTextField jtxtnombreEncargadoEntrada;
    public static javax.swing.JTextField jtxtnombreProveedor;
    private javax.swing.JTextField jtxtnroEntrada;
    public static javax.swing.JTextField jtxtprecioVenta;
    // End of variables declaration//GEN-END:variables

    private void habilitarControles(boolean b) {
        JTextField[] arrJTexFields = {jtxtprecioVenta, jtxtcantidad};
        for (JTextField obJTextField : arrJTexFields) {
            obJTextField.setEditable(b);
        }
        jtxtnroEntrada.grabFocus();
        btnGuardar.setEnabled(b);
        btnCancelar.setEnabled(b);
        btnNuevo.setEnabled(!b);
        btnEliminarProducto.setEnabled(b);
        btnbuscarProveedor.setEnabled(b);
        btnBuscarEncargado.setEnabled(b);
        btnBuscarProducto.setEnabled(b);
        btnEliminarProducto.setEnabled(b);
        jradContado.setEnabled(b);
        jradCredito.setEnabled(b);
    }

    private void limpiarControles() {
        limpiarJTable();
        JTextField[] objTextFields = {jtxtnroEntrada, jtxtcodigoProveedor, jtxtnombreProveedor, jtxtcodigoEncargadoEntrada,
            jtxtnombreEncargadoEntrada, jtxtcodigoProductoEntrada, jtxtDescrProducto, jtxtprecioVenta, jtxtcantidad, jtxtTotal};
        for (JTextField objTextField : objTextFields) {
            objTextField.setText(null);
        }
    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }

    private void calcularTotales() {
        subTotal = 0;
        total = 0;
        int filas = objDtm.getRowCount();
        int cont = 0;
        while (cont < filas) {
            total = total + Double.parseDouble(objDtm.getValueAt(cont, 4).toString());
            cont++;
        }
        jtxtTotal.setText(String.format("%.2f", total));
    }

    private void limpiarProducto() {
        JTextField[] objTextFields = {jtxtcodigoProductoEntrada, jtxtDescrProducto, jtxtprecioVenta, jtxtcantidad};
        for (JTextField objTextField : objTextFields) {
            objTextField.setText(null);
        }
        jcomboxUnidadMedida.removeAllItems();
        jcomboxPresentacion.removeAllItems();
        cantidad = 0;
        precio = 0;
        importe = 0;
    }

    private void llenarComboUDM() {
        try {
            jcomboxPresentacion.removeAllItems();
            String xnombre = jcomboxUnidadMedida.getSelectedItem().toString();
            rspresentacion = objPresentacionDAO.buscarPresentacion(xnombre);
            while (rspresentacion.next()) {
                jcomboxPresentacion.addItem(rspresentacion.getString(3));
            }
        } catch (Exception e) {
        }
    }

    public String jcheckSelecionar() {
        if (jradContado.isSelected()) {
            op = "CONTADO";
        } else {
            op = "CREDITO";
        }
        return op;
    }
}
