/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.Pago_EntradaDAO;
import DAO.Det_PagoEntradaDAO;
import DAO.DetalleEntradaDAO;
import DAO.EntradaDAO;
import DTO.Det_PagoEntradaTO;
import Library.ValidarClass;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEFREY
 */
public class PagoEntradaGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarProductoGUI
     */
    EntradaDAO objEntradaDAO = new EntradaDAO();
    DetalleEntradaDAO objDetalleEntradaDAO = new DetalleEntradaDAO();
    Pago_EntradaDAO objCreditoDAO = new Pago_EntradaDAO();
    Det_PagoEntradaDAO objDetalleCreditoDAO = new Det_PagoEntradaDAO();
    Det_PagoEntradaTO objDetallePago_EntradaTO = new Det_PagoEntradaTO();

    ResultSet rsTipoPago, rsCredito;

    boolean sw;
    int xidproveedor, xidtipopago, xidcredito;
    static double total;

    static double xabono, xmontototal, xsaldoactual;
    ValidarClass objValidarClass = new ValidarClass();
    DefaultTableModel objDtm;
    Calendar objfecha_actual = new GregorianCalendar();

    public PagoEntradaGUI() {
        initComponents();
        setVisible(true);
        setSize(934, 533);
        objDtm = (DefaultTableModel) jtblCreditoProveedor.getModel();
        this.getContentPane().setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuRegistroPago = new javax.swing.JPopupMenu();
        jMenuItemImprimir = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabelRegistro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCreditoProveedor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jlabelnombreProveedor1 = new javax.swing.JLabel();
        jlabelnombreProveedor = new javax.swing.JLabel();
        btnBuscarCredito = new javax.swing.JButton();
        jtxtcodigoProveedor = new javax.swing.JTextField();
        btnbuscarCliente = new javax.swing.JButton();
        jtxtnombreProveedor = new javax.swing.JTextField();
        jlabelnombreProveedor5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlabelnombreProveedor2 = new javax.swing.JLabel();
        jtxtMontoTotal = new javax.swing.JTextField();
        jlabelnombreProveedor4 = new javax.swing.JLabel();
        jtxtSaldoActual = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jlabelnombreProveedor6 = new javax.swing.JLabel();
        jtxtcodigoPagoEntrada = new javax.swing.JTextField();
        jtxtAbono = new javax.swing.JTextField();
        jlabelnombreProveedor3 = new javax.swing.JLabel();
        jtxtDescripcionPago = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jlabelnombreProveedor7 = new javax.swing.JLabel();
        jtxtTotalGeneral = new javax.swing.JTextField();
        jlabelnombreProveedor10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jlabelnombreProveedor8 = new javax.swing.JLabel();
        jlabelnombreProveedor9 = new javax.swing.JLabel();
        jtxtcodigoEncargado = new javax.swing.JTextField();
        btnbuscarEncargado = new javax.swing.JButton();
        jtxtnombreEncargado = new javax.swing.JTextField();

        jMenuItemImprimir.setText("Imprimir");
        jMenuItemImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImprimirActionPerformed(evt);
            }
        });
        jPopupMenuRegistroPago.add(jMenuItemImprimir);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabelRegistro.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabelRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistro.setText("REGISTRO DE PAGO DE ENTRADAS");
        jLabelRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelRegistro)
                .addGap(5, 5, 5))
        );

        jtblCreditoProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "ENCARGADO - ENTRADA", "FECHA", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblCreditoProveedor.setComponentPopupMenu(jPopupMenuRegistroPago);
        jtblCreditoProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblCreditoProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblCreditoProveedor);
        if (jtblCreditoProveedor.getColumnModel().getColumnCount() > 0) {
            jtblCreditoProveedor.getColumnModel().getColumn(0).setMinWidth(70);
            jtblCreditoProveedor.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtblCreditoProveedor.getColumnModel().getColumn(0).setMaxWidth(70);
            jtblCreditoProveedor.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtblCreditoProveedor.getColumnModel().getColumn(2).setPreferredWidth(120);
            jtblCreditoProveedor.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setOpaque(false);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nuevo.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addGap(10, 10, 10))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setOpaque(false);

        jlabelnombreProveedor1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor1.setText("BUSCAR PROVEEDOR:");

        jlabelnombreProveedor.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor.setText("CODIGO:");

        btnBuscarCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pagoefectivo.png"))); // NOI18N
        btnBuscarCredito.setEnabled(false);
        btnBuscarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCreditoActionPerformed(evt);
            }
        });

        jtxtcodigoProveedor.setEditable(false);
        jtxtcodigoProveedor.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoProveedorActionPerformed(evt);
            }
        });
        jtxtcodigoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoProveedorKeyTyped(evt);
            }
        });

        btnbuscarCliente.setText("BUSCAR");
        btnbuscarCliente.setEnabled(false);
        btnbuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarClienteActionPerformed(evt);
            }
        });

        jtxtnombreProveedor.setEditable(false);
        jtxtnombreProveedor.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreProveedorActionPerformed(evt);
            }
        });
        jtxtnombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreProveedorKeyTyped(evt);
            }
        });

        jlabelnombreProveedor5.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor5.setText("ENTRADAS:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jtxtcodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlabelnombreProveedor5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCredito)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelnombreProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtnombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelnombreProveedor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelnombreProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnbuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabelnombreProveedor5))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBuscarCredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtcodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelnombreProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);

        jlabelnombreProveedor2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor2.setText("MONTO:");

        jtxtMontoTotal.setEditable(false);
        jtxtMontoTotal.setBackground(new java.awt.Color(255, 255, 102));
        jtxtMontoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMontoTotalActionPerformed(evt);
            }
        });
        jtxtMontoTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtMontoTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMontoTotalKeyTyped(evt);
            }
        });

        jlabelnombreProveedor4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor4.setText("SALDO:");

        jtxtSaldoActual.setEditable(false);
        jtxtSaldoActual.setBackground(new java.awt.Color(255, 204, 204));
        jtxtSaldoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSaldoActualActionPerformed(evt);
            }
        });
        jtxtSaldoActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSaldoActualKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSaldoActualKeyTyped(evt);
            }
        });

        jLabelDireccion.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelDireccion.setText("DESCRIPCION DEL PAGO:");

        jlabelnombreProveedor6.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor6.setText("CODIGO:");

        jtxtcodigoPagoEntrada.setEditable(false);
        jtxtcodigoPagoEntrada.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoPagoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoPagoEntradaActionPerformed(evt);
            }
        });
        jtxtcodigoPagoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoPagoEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoPagoEntradaKeyTyped(evt);
            }
        });

        jtxtAbono.setEditable(false);
        jtxtAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAbonoActionPerformed(evt);
            }
        });
        jtxtAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtAbonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAbonoKeyTyped(evt);
            }
        });

        jlabelnombreProveedor3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor3.setText("PAGAR:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcodigoPagoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelnombreProveedor6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelnombreProveedor2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelnombreProveedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDireccion)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(186, 186, 186)
                                    .addComponent(jlabelnombreProveedor4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jtxtDescripcionPago, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelnombreProveedor6)
                    .addComponent(jlabelnombreProveedor2)
                    .addComponent(jlabelnombreProveedor3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoPagoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtDescripcionPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelnombreProveedor4)
                    .addComponent(jtxtSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setOpaque(false);

        jlabelnombreProveedor7.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor7.setText("TOTAL:");

        jtxtTotalGeneral.setEditable(false);
        jtxtTotalGeneral.setBackground(new java.awt.Color(204, 204, 204));
        jtxtTotalGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalGeneralActionPerformed(evt);
            }
        });
        jtxtTotalGeneral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTotalGeneralKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTotalGeneralKeyTyped(evt);
            }
        });

        jlabelnombreProveedor10.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor10.setText("S/.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelnombreProveedor10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelnombreProveedor7)
                    .addComponent(jtxtTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jlabelnombreProveedor10))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jlabelnombreProveedor7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setOpaque(false);

        jlabelnombreProveedor8.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor8.setText("BUSCAR ENCARGADO:");

        jlabelnombreProveedor9.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor9.setText("CODIGO:");

        jtxtcodigoEncargado.setEditable(false);
        jtxtcodigoEncargado.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoEncargadoActionPerformed(evt);
            }
        });
        jtxtcodigoEncargado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoEncargadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoEncargadoKeyTyped(evt);
            }
        });

        btnbuscarEncargado.setText("BUSCAR");
        btnbuscarEncargado.setEnabled(false);
        btnbuscarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarEncargadoActionPerformed(evt);
            }
        });

        jtxtnombreEncargado.setEditable(false);
        jtxtnombreEncargado.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreEncargadoActionPerformed(evt);
            }
        });
        jtxtnombreEncargado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreEncargadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreEncargadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jtxtcodigoEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscarEncargado))
                    .addComponent(jlabelnombreProveedor8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtnombreEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelnombreProveedor9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelnombreProveedor9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscarEncargado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcodigoEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelnombreProveedor8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnombreEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            /*DETALLE CREDITO*/
            objDetallePago_EntradaTO.setIdpagoent(Integer.parseInt(jtxtcodigoPagoEntrada.getText()));
            objDetallePago_EntradaTO.setIdencargado(Integer.parseInt(jtxtcodigoEncargado.getText()));
            objDetallePago_EntradaTO.setAbono(Double.parseDouble(jtxtAbono.getText().trim()));
            objDetallePago_EntradaTO.setDescrpago(jtxtDescripcionPago.getText().toUpperCase().trim());
            objDetalleCreditoDAO.insert(objDetallePago_EntradaTO);
            habilitarControles(false);
            JOptionPane.showMessageDialog(rootPane, "CREDITO GRABADO");
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitarControles(true);
        limpiarControles();
        sw = true;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jtxtcodigoProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProveedorKeyReleased

    }//GEN-LAST:event_jtxtcodigoProveedorKeyReleased

    private void jtxtcodigoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProveedorKeyTyped

    private void jtxtMontoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMontoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMontoTotalActionPerformed

    private void jtxtMontoTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMontoTotalKeyReleased

    }//GEN-LAST:event_jtxtMontoTotalKeyReleased

    private void jtxtMontoTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMontoTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMontoTotalKeyTyped

    private void btnbuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarClienteActionPerformed
        BPV_PagoEntradaGUI pv = new BPV_PagoEntradaGUI();
        MenuGUI.desktopPane.add(pv);
        pv.setVisible(true);
        pv.setLocation(500, 150);
        pv.setSize(530, 310);
        pv.toFront();
    }//GEN-LAST:event_btnbuscarClienteActionPerformed

    private void jtblCreditoProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblCreditoProveedorMouseClicked
        try {
            xidcredito = Integer.parseInt(jtblCreditoProveedor.getValueAt(jtblCreditoProveedor.getSelectedRow(), 0).toString());
            rsCredito.first();
            do {
                if (xidcredito == rsCredito.getInt(1)) {
                    jtxtcodigoPagoEntrada.setText(rsCredito.getString(1));
                    jtxtMontoTotal.setText(rsCredito.getString(5));
                    rsCredito.last();
                }
            } while (rsCredito.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jtblCreditoProveedorMouseClicked

    private void jtxtnombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorActionPerformed

    private void jtxtnombreProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorKeyReleased

    private void jtxtnombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorKeyTyped

    private void jtxtSaldoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSaldoActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSaldoActualActionPerformed

    private void jtxtSaldoActualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSaldoActualKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSaldoActualKeyReleased

    private void jtxtSaldoActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSaldoActualKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSaldoActualKeyTyped

    private void jtxtTotalGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalGeneralActionPerformed

    private void jtxtTotalGeneralKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalGeneralKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalGeneralKeyReleased

    private void jtxtTotalGeneralKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalGeneralKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalGeneralKeyTyped

    private void jtxtcodigoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProveedorActionPerformed

    private void jMenuItemImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImprimirActionPerformed

    }//GEN-LAST:event_jMenuItemImprimirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtcodigoPagoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoPagoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoPagoEntradaActionPerformed

    private void jtxtcodigoPagoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoPagoEntradaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoPagoEntradaKeyReleased

    private void jtxtcodigoPagoEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoPagoEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoPagoEntradaKeyTyped

    private void jtxtAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAbonoActionPerformed
        xmontototal = Double.parseDouble(jtxtMontoTotal.getText().trim());
        xabono = Double.parseDouble(jtxtAbono.getText().trim());
        xsaldoactual = xmontototal - xabono;
        jtxtSaldoActual.setText(String.format("%.2f", xsaldoactual));
    }//GEN-LAST:event_jtxtAbonoActionPerformed

    private void jtxtAbonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAbonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAbonoKeyReleased

    private void jtxtAbonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAbonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAbonoKeyTyped

    private void jtxtcodigoEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoActionPerformed

    private void jtxtcodigoEncargadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoKeyReleased

    private void jtxtcodigoEncargadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoKeyTyped

    private void btnbuscarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarEncargadoActionPerformed
        BE_PagoEntradaGUI e = new BE_PagoEntradaGUI();
        MenuGUI.desktopPane.add(e);
        e.setVisible(true);
        e.setLocation(500, 150);
        e.setSize(530, 310);
        e.toFront();
    }//GEN-LAST:event_btnbuscarEncargadoActionPerformed

    private void jtxtnombreEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoActionPerformed

    private void jtxtnombreEncargadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoKeyReleased

    private void jtxtnombreEncargadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoKeyTyped

    private void btnBuscarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCreditoActionPerformed
        try {
            limpiarJTable();
            xidproveedor = Integer.parseInt(jtxtcodigoProveedor.getText().trim());
            rsCredito = objCreditoDAO.buscarCreditoProveedor(xidproveedor);
            while (rsCredito.next()) {
                Object[] registro = {rsCredito.getInt(1),rsCredito.getString(3),
                    rsCredito.getDate(4), rsCredito.getString(5)};
                objDtm.addRow(registro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        calcularTotalGeneral();
    }//GEN-LAST:event_btnBuscarCreditoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCredito;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnbuscarCliente;
    private javax.swing.JButton btnbuscarEncargado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JMenuItem jMenuItemImprimir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenuRegistroPago;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelnombreProveedor;
    private javax.swing.JLabel jlabelnombreProveedor1;
    private javax.swing.JLabel jlabelnombreProveedor10;
    private javax.swing.JLabel jlabelnombreProveedor2;
    private javax.swing.JLabel jlabelnombreProveedor3;
    private javax.swing.JLabel jlabelnombreProveedor4;
    private javax.swing.JLabel jlabelnombreProveedor5;
    private javax.swing.JLabel jlabelnombreProveedor6;
    private javax.swing.JLabel jlabelnombreProveedor7;
    private javax.swing.JLabel jlabelnombreProveedor8;
    private javax.swing.JLabel jlabelnombreProveedor9;
    private javax.swing.JTable jtblCreditoProveedor;
    public static javax.swing.JTextField jtxtAbono;
    private javax.swing.JTextField jtxtDescripcionPago;
    public static javax.swing.JTextField jtxtMontoTotal;
    public static javax.swing.JTextField jtxtSaldoActual;
    public static javax.swing.JTextField jtxtTotalGeneral;
    public static javax.swing.JTextField jtxtcodigoEncargado;
    public static javax.swing.JTextField jtxtcodigoPagoEntrada;
    public static javax.swing.JTextField jtxtcodigoProveedor;
    public static javax.swing.JTextField jtxtnombreEncargado;
    public static javax.swing.JTextField jtxtnombreProveedor;
    // End of variables declaration//GEN-END:variables

    private void habilitarControles(boolean b) {
        JTextField[] arrJTexFields = {jtxtAbono};
        for (JTextField obJTextField : arrJTexFields) {
            obJTextField.setEditable(b);
        }
        btnGuardar.setEnabled(b);
        btnCancelar.setEnabled(b);
        btnNuevo.setEnabled(!b);
        btnbuscarCliente.setEnabled(b);
        btnBuscarCredito.setEnabled(b);
        btnbuscarEncargado.setEnabled(b);
    }

    private void limpiarControles() {
        limpiarJTable();
        JTextField[] objTextFields = {jtxtcodigoProveedor, jtxtnombreProveedor, jtxtcodigoPagoEntrada,
            jtxtAbono, jtxtMontoTotal, jtxtSaldoActual};
        for (JTextField objTextField : objTextFields) {
            objTextField.setText(null);
        }
        jtxtDescripcionPago.setText(null);
    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }

    private void calcularTotalGeneral() {
        total = 0;
        int filas = objDtm.getRowCount();
        int cont = 0;
        while (cont < filas) {
            total = total + Double.parseDouble(objDtm.getValueAt(cont, 3).toString());
            cont++;
        }
        jtxtTotalGeneral.setText(String.format("%.2f", total));
    }
}
