/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import GUI.Producto.BP_PreprecioGUI;
import DAO.DetalleEntradaDAO;
import DAO.EntradaDAO;
import DAO.ProveedorDAO;
import DTO.DetalleEntradaTO;
import DTO.EntradaTO;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEFREY
 */
public class SalidaGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductoGUI2
     */
    EntradaDAO objEntradaDAO = new EntradaDAO();
    DetalleEntradaDAO objDetalleEntradaDAO = new DetalleEntradaDAO();
    ProveedorDAO objProveedorDAO = new ProveedorDAO();
    JRootPane rootPane;
    boolean sw;
    DefaultTableModel objDtm;
    ResultSet rsProducto, rsProveedor;
    int xidproducto, xidproveedor, xidentrada;

    double precio;
    int cantidad;
    double importe;
    static double subTotal;
    static double igv;
    static double total;

    public SalidaGUI() {
        initComponents();
        setVisible(true);
        this.setSize(710, 610);
        objDtm = (DefaultTableModel) jtblEntrada.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jlabelprecioCompra = new javax.swing.JLabel();
        jtxtprecioCompra = new javax.swing.JTextField();
        jlabelCantidad = new javax.swing.JLabel();
        jtxtcantidad = new javax.swing.JTextField();
        jlabelCantidad1 = new javax.swing.JLabel();
        jtxtImporte = new javax.swing.JTextField();
        jbtnAgregar1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jlabelcodigoProducto = new javax.swing.JLabel();
        jtxtnombreProducto = new javax.swing.JTextField();
        jlabelDescProducto = new javax.swing.JLabel();
        jtxtcodigoProducto = new javax.swing.JTextField();
        jbtnBuscarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEntrada = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlabelTotal = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jlabelTotal1 = new javax.swing.JLabel();
        jlabelTotal2 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtIGV = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jtxtnombreProveedor = new javax.swing.JTextField();
        jlabelnombreProveedor = new javax.swing.JLabel();
        jbtnbuscarProveedor = new javax.swing.JButton();
        jlabelnombreProveedor1 = new javax.swing.JLabel();
        jtxtcodigoProveedor = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jlabelnumDocumento1 = new javax.swing.JLabel();
        jtxtnumBoleta = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("AREA DE ENTRADAS");
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlabelprecioCompra.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelprecioCompra.setText("P.COMPRA:");

        jtxtprecioCompra.setEditable(false);
        jtxtprecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtprecioCompraActionPerformed(evt);
            }
        });
        jtxtprecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtprecioCompraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtprecioCompraKeyTyped(evt);
            }
        });

        jlabelCantidad.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelCantidad.setText("CANTIDAD:");

        jtxtcantidad.setEditable(false);
        jtxtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcantidadActionPerformed(evt);
            }
        });
        jtxtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcantidadKeyTyped(evt);
            }
        });

        jlabelCantidad1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelCantidad1.setText("IMPORTE:");

        jtxtImporte.setEditable(false);
        jtxtImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtImporteActionPerformed(evt);
            }
        });
        jtxtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtImporteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtImporteKeyTyped(evt);
            }
        });

        jbtnAgregar1.setText("AGREGAR");
        jbtnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlabelprecioCompra)
                .addGap(10, 10, 10)
                .addComponent(jtxtprecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jlabelCantidad)
                .addGap(10, 10, 10)
                .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jlabelCantidad1)
                .addGap(10, 10, 10)
                .addComponent(jtxtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbtnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelprecioCompra)
                    .addComponent(jlabelCantidad1)
                    .addComponent(jtxtprecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelCantidad)
                    .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAgregar1))
                .addGap(5, 5, 5))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlabelcodigoProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelcodigoProducto.setText("CODIGO:");

        jtxtnombreProducto.setEditable(false);
        jtxtnombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreProductoKeyTyped(evt);
            }
        });

        jlabelDescProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelDescProducto.setText("DESCRIPCION PRODUCTO:");

        jtxtcodigoProducto.setEditable(false);
        jtxtcodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoProductoActionPerformed(evt);
            }
        });
        jtxtcodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoProductoKeyTyped(evt);
            }
        });

        jbtnBuscarProducto.setText("BUSCAR");
        jbtnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtcodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelcodigoProducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jtxtnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnBuscarProducto))
                    .addComponent(jlabelDescProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelcodigoProducto)
                    .addComponent(jlabelDescProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBuscarProducto))
                .addGap(5, 5, 5))
        );

        jtblEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "DESCRIPCION", "PCOMPRA", "CANTIDAD", "SUB TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblEntrada);
        if (jtblEntrada.getColumnModel().getColumnCount() > 0) {
            jtblEntrada.getColumnModel().getColumn(0).setResizable(false);
            jtblEntrada.getColumnModel().getColumn(1).setResizable(false);
            jtblEntrada.getColumnModel().getColumn(2).setResizable(false);
            jtblEntrada.getColumnModel().getColumn(3).setResizable(false);
            jtblEntrada.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nuevo.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salida.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir))
                .addGap(10, 10, 10))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlabelTotal.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal.setText("TOTAL:");

        jtxtTotal.setEditable(false);
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jtxtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTotalKeyTyped(evt);
            }
        });

        jlabelTotal1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal1.setText("IGV:");

        jlabelTotal2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal2.setText("SUBTOTAL:");

        jtxtSubTotal.setEditable(false);
        jtxtSubTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSubTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSubTotalKeyTyped(evt);
            }
        });

        jtxtIGV.setEditable(false);
        jtxtIGV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtIGVKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtIGVKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelTotal1)
                    .addComponent(jlabelTotal2))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtIGV, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelTotal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelTotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelTotal)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtxtnombreProveedor.setEditable(false);
        jtxtnombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreProveedorActionPerformed(evt);
            }
        });
        jtxtnombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreProveedorKeyTyped(evt);
            }
        });

        jlabelnombreProveedor.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor.setText("CODIGO:");

        jbtnbuscarProveedor.setText("BUSCAR");
        jbtnbuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbuscarProveedorActionPerformed(evt);
            }
        });

        jlabelnombreProveedor1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor1.setText("DESCRIPCION PROVEEDOR:");

        jtxtcodigoProveedor.setEditable(false);
        jtxtcodigoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoProveedorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtcodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelnombreProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jtxtnombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnbuscarProveedor))
                    .addComponent(jlabelnombreProveedor1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelnombreProveedor)
                    .addComponent(jlabelnombreProveedor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtnombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnbuscarProveedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlabelnumDocumento1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnumDocumento1.setText("NºDOCUMENTO:");

        jtxtnumBoleta.setEditable(false);
        jtxtnumBoleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnumBoletaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnumBoletaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtnumBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelnumDocumento1))
                .addGap(5, 5, 5))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlabelnumDocumento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnumBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProductoKeyTyped

    private void jtxtnombreProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProductoKeyReleased

    private void jtxtcodigoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProveedorKeyTyped

    private void jtxtcodigoProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProveedorKeyReleased

    private void jtxtnombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorKeyTyped

    private void jtxtnombreProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorKeyReleased

    private void jtxtcodigoProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoKeyReleased

    private void jtxtcodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoKeyTyped

    private void jtxtprecioCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtprecioCompraKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtprecioCompraKeyReleased

    private void jtxtprecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtprecioCompraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtprecioCompraKeyTyped

    private void jtxtImporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtImporteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtImporteKeyReleased

    private void jtxtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtImporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtImporteKeyTyped

    private void jtxtnombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProveedorActionPerformed

    private void jtxtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalKeyReleased

    private void jtxtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalKeyTyped

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            /*ENTRADA*/
            EntradaTO objEntradaTO = new EntradaTO();
            objEntradaTO.setIdproveedor(Integer.parseInt(jtxtcodigoProveedor.getText()));
//            objEntradaTO.setNumboleta(jtxtnumBoleta.getText());
            objEntradaTO.setTotalent(total);
            objEntradaDAO.insert(objEntradaTO);
            xidentrada = objEntradaDAO.obternerIDIngreso();
            /*DETALLE ENTRADA*/
            int filas = objDtm.getRowCount();
            for (int i = 0; i < filas; i++) {
                DetalleEntradaTO objDetalleEntradaTO = new DetalleEntradaTO();
                objDetalleEntradaTO.setIdentrada(xidentrada);
                objDetalleEntradaTO.setIdproducto(Integer.parseInt(jtblEntrada.getValueAt(i, 0).toString()));
                objDetalleEntradaTO.setPcompraent(Double.parseDouble(jtblEntrada.getValueAt(i, 2).toString()));
                objDetalleEntradaTO.setCantidadent(Integer.parseInt(jtblEntrada.getValueAt(i, 3).toString()));
                objDetalleEntradaTO.setImporteent(Double.parseDouble(jtblEntrada.getValueAt(i, 4).toString()));
                objDetalleEntradaDAO.insert(objDetalleEntradaTO);
            }
            habilitarControles(false);
            JOptionPane.showMessageDialog(rootPane, "ENTRADA GRABADO");
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jbtnbuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbuscarProveedorActionPerformed
        MenuGUI.desktopPane.add(new BuscarProveedorGUI());
    }//GEN-LAST:event_jbtnbuscarProveedorActionPerformed

    private void jbtnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarProductoActionPerformed
        MenuGUI.desktopPane.add(new BP_PreprecioGUI());
    }//GEN-LAST:event_jbtnBuscarProductoActionPerformed

    private void jtxtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcantidadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcantidadKeyReleased

    private void jtxtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcantidadKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitarControles(true);
        limpiarControles();
//        establecerLabel();
        sw = true;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        habilitarControles(true);
        sw = false;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jbtnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregar1ActionPerformed
        if (importe == 0) {
            JOptionPane.showMessageDialog(rootPane, "REGISTRAR LOS PRODUCTOS");
        } else {
             sw = false;
            int cont = 0;
            int idproducto = Integer.parseInt(jtxtcodigoProducto.getText());
            Object registro[] = {jtxtcodigoProducto.getText(), jtxtnombreProducto.getText(), precio,
                cantidad, importe};
            if (objDtm.getRowCount() == 0) {
                objDtm.addRow(registro);
                limpiarProducto();
            } else {
                while (cont < objDtm.getRowCount()) {
                    if (idproducto == Integer.parseInt(objDtm.getValueAt(cont, 0).toString())) {
                        JOptionPane.showMessageDialog(rootPane, "REGISTRO YA EXISTE");
                        sw = true;
                    }
                    cont++;
                }
                if (!sw) {
                    objDtm.addRow(registro);
                }
            }
            limpiarProducto();
        }
        calcularTotales();
    }//GEN-LAST:event_jbtnAgregar1ActionPerformed

    private void jtxtSubTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSubTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalKeyReleased

    private void jtxtSubTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSubTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalKeyTyped

    private void jtxtIGVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIGVKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIGVKeyReleased

    private void jtxtIGVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIGVKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIGVKeyTyped

    private void jtxtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcantidadActionPerformed
        precio = Double.parseDouble(jtxtprecioCompra.getText().trim());
        cantidad = Integer.parseInt(jtxtcantidad.getText().trim());
        importe = precio * cantidad;
        jtxtImporte.setText(String.format("%.2f", importe));    }//GEN-LAST:event_jtxtcantidadActionPerformed

    private void jtxtcodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoActionPerformed

    private void jtxtprecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtprecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtprecioCompraActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtxtnumBoletaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnumBoletaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnumBoletaKeyReleased

    private void jtxtnumBoletaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnumBoletaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnumBoletaKeyTyped

    private void jtxtImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtImporteActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAgregar1;
    private javax.swing.JButton jbtnBuscarProducto;
    private javax.swing.JButton jbtnbuscarProveedor;
    private javax.swing.JLabel jlabelCantidad;
    private javax.swing.JLabel jlabelCantidad1;
    private javax.swing.JLabel jlabelDescProducto;
    private javax.swing.JLabel jlabelTotal;
    private javax.swing.JLabel jlabelTotal1;
    private javax.swing.JLabel jlabelTotal2;
    private javax.swing.JLabel jlabelcodigoProducto;
    private javax.swing.JLabel jlabelnombreProveedor;
    private javax.swing.JLabel jlabelnombreProveedor1;
    private javax.swing.JLabel jlabelnumDocumento1;
    private javax.swing.JLabel jlabelprecioCompra;
    private javax.swing.JTable jtblEntrada;
    private javax.swing.JTextField jtxtIGV;
    private javax.swing.JTextField jtxtImporte;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtcantidad;
    public static javax.swing.JTextField jtxtcodigoProducto;
    public static javax.swing.JTextField jtxtcodigoProveedor;
    public static javax.swing.JTextField jtxtnombreProducto;
    public static javax.swing.JTextField jtxtnombreProveedor;
    private javax.swing.JTextField jtxtnumBoleta;
    private javax.swing.JTextField jtxtprecioCompra;
    // End of variables declaration//GEN-END:variables

    private void habilitarControles(boolean b) {
        JTextField[] arrJTexFields = {jtxtnumBoleta,
            jtxtprecioCompra, jtxtcantidad, jtxtTotal};
        for (JTextField obJTextField : arrJTexFields) {
            obJTextField.setEditable(b);
        }
        jtxtnumBoleta.grabFocus();
        btnGuardar.setEnabled(b);
        btnCancelar.setEnabled(b);
        btnNuevo.setEnabled(!b);
        btnEditar.setEnabled(!b);
        btnEliminar.setEnabled(!b);
        btnSalir.setEnabled(!b);

    }

    private void limpiarControles() {
        limpiarJTable();
        JTextField[] objTextFields = {jtxtcodigoProveedor, jtxtnombreProveedor, jtxtcodigoProducto,
            jtxtnombreProducto, jtxtprecioCompra, jtxtcantidad, jtxtTotal};
        for (JTextField objTextField : objTextFields) {
            objTextField.setText(null);
        }

    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }

//    private void establecerLabel() {
//      JLabel[] arrJLabel = {jlabelnumDocumento,jlabelnombreProveedor,jlabelcodigoProducto,jlabelcodigoProducto,
//      jlabelprecioCompra,jlabelCantidad,jlabelTotal};
//      for (JLabel objJLabel: arrJLabel) {
//            objJLabel.setForeground(null);
//        }
//    }
    private void calcularTotales() {
        subTotal = 0;
        igv = 0;
        total = 0;
        int filas = objDtm.getRowCount();
        int cont = 0;
        while (cont < filas) {
            total = total + Double.parseDouble(objDtm.getValueAt(cont, 4).toString());
            cont++;
        }
        subTotal = total / 1.18;
        igv = total - subTotal;
        jtxtSubTotal.setText(String.format("%.2f", subTotal));
        jtxtIGV.setText(String.format("%.2f", igv));
        jtxtTotal.setText(String.format("%.2f", total));
    }

    private void limpiarProducto() {
        jtxtcodigoProducto.setText(null);
        jtxtnombreProducto.setText(null);
        jtxtprecioCompra.setText(null);
        jtxtcantidad.setText(null);
        jtxtImporte.setText(null);
        cantidad = 0;
        precio = 0;
        importe = 0;
    }
}
