/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.Producto;

import DAO.PrePrecioDAO;
import DAO.PresentacionDAO;
import DAO.UnidadMedidaDAO;
import DTO.PrePrecioTO;
import DTO.PresentacionTO;
import DTO.UnidadMedidaTO;
import GUI.MenuGUI;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEFREY
 */
public class PrePrecioGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form UnidadMedidaGUI
     */
    PresentacionDAO objPresentacionDAO = new PresentacionDAO();
    PresentacionTO objPresentacionTO = new PresentacionTO();

    PrePrecioDAO objPrePrecioDAO = new PrePrecioDAO();
    PrePrecioTO objPreprecioTO = new PrePrecioTO();
    UnidadMedidaDAO objUnidadMedidaDAO = new UnidadMedidaDAO();
    UnidadMedidaTO objUnidadMedidaTO = new UnidadMedidaTO();
    JRootPane rootPane;
    boolean sw;
    DefaultTableModel objDtm;
    ResultSet rsUnidadMedida, rsPreprecio, rsPresentacion;
    int xidunidadmedida, xidpresentacion, xidpreprecio;
    String mensaje;

    public PrePrecioGUI() {
        initComponents();
        setVisible(true);
        setSize(1091, 437);
        this.getContentPane().setBackground(Color.white);
        objDtm = (DefaultTableModel) jtblRegistroPreprecio.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistro = new javax.swing.JPanel();
        jLabelRegistroPresentacion = new javax.swing.JLabel();
        jPanelDatosPresentacion = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelUnidadMedida = new javax.swing.JLabel();
        jtxtCodPreprecio = new javax.swing.JTextField();
        jPanelBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jLabelPresentacion = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jtxtPrecio = new javax.swing.JTextField();
        jcomboxUnidadMedida = new javax.swing.JComboBox<>();
        jtxtDescripcionProducto = new javax.swing.JTextField();
        jLabelDescripcionProducto = new javax.swing.JLabel();
        jbtnBuscarProducto = new javax.swing.JButton();
        jLabelUnidadMedida1 = new javax.swing.JLabel();
        jcomboxPresentacion = new javax.swing.JComboBox<>();
        jLabelCodigo1 = new javax.swing.JLabel();
        jtxtCodProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistroPreprecio = new javax.swing.JTable();
        jPanelBuscar = new javax.swing.JPanel();
        jLabelBuscarPresentacion = new javax.swing.JLabel();
        jtxtBuscarPreprecio = new javax.swing.JTextField();

        jPanelRegistro.setBackground(new java.awt.Color(153, 153, 255));
        jPanelRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabelRegistroPresentacion.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabelRegistroPresentacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroPresentacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistroPresentacion.setText("REGISTRO PRESENTACION DE PRECIO");
        jLabelRegistroPresentacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelRegistroLayout = new javax.swing.GroupLayout(jPanelRegistro);
        jPanelRegistro.setLayout(jPanelRegistroLayout);
        jPanelRegistroLayout.setHorizontalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistroPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanelRegistroLayout.setVerticalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelRegistroPresentacion)
                .addGap(5, 5, 5))
        );

        jPanelDatosPresentacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDatosPresentacion.setOpaque(false);

        jLabelCodigo.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelCodigo.setText("COD:");

        jLabelUnidadMedida.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelUnidadMedida.setText("UNIDAD MEDIDA:");

        jtxtCodPreprecio.setEditable(false);
        jtxtCodPreprecio.setBackground(new java.awt.Color(204, 204, 204));
        jtxtCodPreprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtCodPreprecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCodPreprecioKeyTyped(evt);
            }
        });

        jPanelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBotones.setOpaque(false);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nuevo.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salida.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir))
                .addGap(10, 10, 10))
        );

        jPanelDatos.setBackground(new java.awt.Color(153, 153, 255));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabelPresentacion.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabelPresentacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPresentacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPresentacion.setText("DATOS PRESENTACION DE PRECIO");
        jLabelPresentacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelPresentacion)
                .addGap(5, 5, 5))
        );

        jLabelValor.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelValor.setText("PRECIO:");

        jtxtPrecio.setEditable(false);
        jtxtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrecioActionPerformed(evt);
            }
        });
        jtxtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPrecioKeyTyped(evt);
            }
        });

        jcomboxUnidadMedida.setEnabled(false);
        jcomboxUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboxUnidadMedidaActionPerformed(evt);
            }
        });
        jcomboxUnidadMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcomboxUnidadMedidaKeyReleased(evt);
            }
        });

        jtxtDescripcionProducto.setEditable(false);
        jtxtDescripcionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDescripcionProductoActionPerformed(evt);
            }
        });
        jtxtDescripcionProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtDescripcionProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDescripcionProductoKeyTyped(evt);
            }
        });

        jLabelDescripcionProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelDescripcionProducto.setText("DESCRIPCION DEL PRODUCTO:");

        jbtnBuscarProducto.setText("BUSCAR");
        jbtnBuscarProducto.setEnabled(false);
        jbtnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarProductoActionPerformed(evt);
            }
        });

        jLabelUnidadMedida1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelUnidadMedida1.setText("PRESENTACION:");

        jcomboxPresentacion.setEnabled(false);
        jcomboxPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboxPresentacionActionPerformed(evt);
            }
        });
        jcomboxPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcomboxPresentacionKeyReleased(evt);
            }
        });

        jLabelCodigo1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelCodigo1.setText("COD-P:");

        jtxtCodProducto.setEditable(false);
        jtxtCodProducto.setBackground(new java.awt.Color(204, 204, 204));
        jtxtCodProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtCodProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCodProductoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosPresentacionLayout = new javax.swing.GroupLayout(jPanelDatosPresentacion);
        jPanelDatosPresentacion.setLayout(jPanelDatosPresentacionLayout);
        jPanelDatosPresentacionLayout.setHorizontalGroup(
            jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDatosPresentacionLayout.createSequentialGroup()
                .addGroup(jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPresentacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelUnidadMedida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcomboxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosPresentacionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCodigo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtCodPreprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jbtnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPresentacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescripcionProducto)
                            .addGroup(jPanelDatosPresentacionLayout.createSequentialGroup()
                                .addGroup(jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcomboxPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelUnidadMedida1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelValor)
                                    .addComponent(jtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelDatosPresentacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtDescripcionProducto)))
                .addContainerGap())
            .addGroup(jPanelDatosPresentacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosPresentacionLayout.setVerticalGroup(
            jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPresentacionLayout.createSequentialGroup()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jtxtCodPreprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigo1)
                    .addComponent(jtxtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabelDescripcionProducto)
                .addGap(5, 5, 5)
                .addComponent(jtxtDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnidadMedida))
                .addGap(10, 10, 10)
                .addGroup(jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUnidadMedida1)
                    .addComponent(jLabelValor))
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboxPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtblRegistroPreprecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "UDM", "DESCRIPCION", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblRegistroPreprecio.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jtblRegistroPreprecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblRegistroPreprecioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblRegistroPreprecio);
        if (jtblRegistroPreprecio.getColumnModel().getColumnCount() > 0) {
            jtblRegistroPreprecio.getColumnModel().getColumn(0).setMinWidth(70);
            jtblRegistroPreprecio.getColumnModel().getColumn(0).setMaxWidth(70);
            jtblRegistroPreprecio.getColumnModel().getColumn(1).setMinWidth(100);
            jtblRegistroPreprecio.getColumnModel().getColumn(1).setMaxWidth(100);
            jtblRegistroPreprecio.getColumnModel().getColumn(2).setMinWidth(350);
            jtblRegistroPreprecio.getColumnModel().getColumn(2).setMaxWidth(350);
            jtblRegistroPreprecio.getColumnModel().getColumn(3).setMinWidth(100);
        }

        jPanelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBuscar.setOpaque(false);

        jLabelBuscarPresentacion.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelBuscarPresentacion.setText("BUSCAR:");

        jtxtBuscarPreprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBuscarPreprecioActionPerformed(evt);
            }
        });
        jtxtBuscarPreprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarPreprecioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelBuscarPresentacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtBuscarPreprecio)
                .addContainerGap())
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBuscarPreprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuscarPresentacion))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanelRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanelDatosPresentacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCodPreprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCodPreprecioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodPreprecioKeyTyped

    private void jtxtCodPreprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCodPreprecioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodPreprecioKeyReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int op = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO QUE DESEA ELIMINAR?", "REGISTRO PRESENTACION DE PRECIOS", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (op == JOptionPane.YES_OPTION) {
                objPreprecioTO.setIdpreprecio(xidpreprecio);
                objPrePrecioDAO.delete(objPreprecioTO);
                limpiarControles();
                JOptionPane.showMessageDialog(null, "REGISTRO ELIMINADO");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtxtBuscarPreprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBuscarPreprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBuscarPreprecioActionPerformed

    private void jtxtBuscarPreprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarPreprecioKeyReleased
        try {
            limpiarJTable();
            if (!jtxtBuscarPreprecio.getText().isEmpty()) {
                rsPreprecio = objPrePrecioDAO.buscar(jtxtBuscarPreprecio.getText().trim());
                while (rsPreprecio.next()) {
                    Object registro[] = {rsPreprecio.getInt(1), rsPreprecio.getString(3), rsPreprecio.getString(5), rsPreprecio.getString(6)};
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jtxtBuscarPreprecioKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitarControles(true);
        limpiarControles();
        sw = true;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (jtxtDescripcionProducto.getText().trim().length() == 0 || jtxtPrecio.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "COMPLETAR CAJA DE TEXTO", "FERRETERIA MICKY", JOptionPane.WARNING_MESSAGE);
            } else {
                objPreprecioTO.setIdproducto(Integer.parseInt(jtxtCodProducto.getText()));
                String descrunid = jcomboxUnidadMedida.getSelectedItem().toString();
                String descrpresent = jcomboxPresentacion.getSelectedItem().toString();
                xidpresentacion = objPrePrecioDAO.obtenerIDPresent(descrunid, descrpresent);
                objPreprecioTO.setIdpresentacion(xidpresentacion);
                objPreprecioTO.setPreprecio(Double.parseDouble(jtxtPrecio.getText().trim()));
                if (sw) {
                    objPrePrecioDAO.insert(objPreprecioTO);
                    mensaje = "PRESENTACION DE PRECIOS REGISTRADO";
                } else {
                    objPreprecioTO.setIdpreprecio(Integer.parseInt(jtxtCodPreprecio.getText()));
                    objPrePrecioDAO.update(objPreprecioTO);
                    mensaje = "PRESENTACION DE PRECIOS ACTUALIZADO";
                }
                habilitarControles(false);
                JOptionPane.showMessageDialog(null, mensaje, "FERRETERIA MICKY", JOptionPane.INFORMATION_MESSAGE);
                limpiarControles();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "FERRETERIA MICKY", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        habilitarControles(true);
        jcomboxPresentacion.setEnabled(true);
        sw = false;
        obtenerDescrUDM();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jtblRegistroPreprecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRegistroPreprecioMouseClicked
        try {
            xidpreprecio = Integer.parseInt(jtblRegistroPreprecio.getValueAt(jtblRegistroPreprecio.getSelectedRow(), 0).toString());
            rsPreprecio.first();
            do {
                if (xidpreprecio == rsPreprecio.getInt(1)) {
                    jtxtCodPreprecio.setText(String.valueOf(rsPreprecio.getInt(1)));
                    jcomboxPresentacion.removeAllItems();
                    jcomboxPresentacion.addItem(rsPreprecio.getString(3));
                    jtxtCodProducto.setText(String.valueOf(rsPreprecio.getInt(4)));
                    jtxtDescripcionProducto.setText(rsPreprecio.getString(5));
                    jtxtPrecio.setText(rsPreprecio.getString(6));
                    rsPreprecio.last();
                }
            } while (rsPreprecio.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtblRegistroPreprecioMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtxtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioActionPerformed

    private void jtxtPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioKeyReleased

    private void jtxtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioKeyTyped

    private void jcomboxUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboxUnidadMedidaActionPerformed
        llenarComboUDM();
    }//GEN-LAST:event_jcomboxUnidadMedidaActionPerformed

    private void jcomboxUnidadMedidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboxUnidadMedidaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboxUnidadMedidaKeyReleased

    private void jtxtDescripcionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDescripcionProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDescripcionProductoActionPerformed

    private void jtxtDescripcionProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDescripcionProductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDescripcionProductoKeyReleased

    private void jtxtDescripcionProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDescripcionProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDescripcionProductoKeyTyped

    private void jbtnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarProductoActionPerformed
        BP_PreprecioGUI objBP_PreprecioGUI = new BP_PreprecioGUI();
        MenuGUI.desktopPane.add(objBP_PreprecioGUI);
        objBP_PreprecioGUI.setVisible(true);
        objBP_PreprecioGUI.setLocation(500, 150);
        objBP_PreprecioGUI.setSize(600, 320);
        objBP_PreprecioGUI.toFront();
    }//GEN-LAST:event_jbtnBuscarProductoActionPerformed

    private void jcomboxPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboxPresentacionActionPerformed

    }//GEN-LAST:event_jcomboxPresentacionActionPerformed

    private void jcomboxPresentacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboxPresentacionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboxPresentacionKeyReleased

    private void jtxtCodProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCodProductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodProductoKeyReleased

    private void jtxtCodProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCodProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodProductoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabelBuscarPresentacion;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelDescripcionProducto;
    private javax.swing.JLabel jLabelPresentacion;
    private javax.swing.JLabel jLabelRegistroPresentacion;
    private javax.swing.JLabel jLabelUnidadMedida;
    private javax.swing.JLabel jLabelUnidadMedida1;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDatosPresentacion;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscarProducto;
    public static javax.swing.JComboBox<String> jcomboxPresentacion;
    public static javax.swing.JComboBox<String> jcomboxUnidadMedida;
    private javax.swing.JTable jtblRegistroPreprecio;
    private javax.swing.JTextField jtxtBuscarPreprecio;
    public static javax.swing.JTextField jtxtCodPreprecio;
    public static javax.swing.JTextField jtxtCodProducto;
    public static javax.swing.JTextField jtxtDescripcionProducto;
    private javax.swing.JTextField jtxtPrecio;
    // End of variables declaration//GEN-END:variables

    private void habilitarControles(boolean b) {
        JTextField[] arrJTexFields = {jtxtPrecio};
        for (JTextField obJTextField : arrJTexFields) {
            obJTextField.setEditable(b);
        }
        jtxtBuscarPreprecio.setEditable(!b);
        btnGuardar.setEnabled(b);
        btnCancelar.setEnabled(b);
        btnNuevo.setEnabled(!b);
        btnEditar.setEnabled(!b);
        jbtnBuscarProducto.setEnabled(b);
        btnEliminar.setEnabled(!b);
        btnSalir.setEnabled(!b);
    }

    private void limpiarControles() {
        limpiarJTable();
        JTextField[] objTextFields = {jtxtCodPreprecio, jtxtCodProducto, jtxtBuscarPreprecio, jtxtDescripcionProducto, jtxtPrecio};
        for (JTextField objTextField : objTextFields) {
            objTextField.setText(null);
        }
        jcomboxPresentacion.removeAllItems();
        jcomboxUnidadMedida.removeAllItems();
    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }
 
    private void obtenerDescrUDM(){
          try {
            String data = String.valueOf(jcomboxPresentacion.getSelectedItem());
            objPrePrecioDAO.buscarUDM(data);
            String resultado = objPrePrecioDAO.buscarUDM(data);
            jcomboxUnidadMedida.removeAllItems();
            jcomboxUnidadMedida.addItem(resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void llenarComboUDM() {
        try {
            jcomboxPresentacion.removeAllItems();
            String xnombre = jcomboxUnidadMedida.getSelectedItem().toString();
            rsPreprecio = objPresentacionDAO.buscarPresentacion(xnombre);
            while (rsPreprecio.next()) {
                jcomboxPresentacion.addItem(rsPreprecio.getString(3));
            }
        } catch (Exception e) {
        }
    }
}
