/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.Producto;

import DAO.CategoriaDAO;
import DAO.PrePrecioDAO;
import DAO.ProductoDAO;
import DAO.UnidadMedidaDAO;
import DTO.PrePrecioTO;
import DTO.ProductoTO;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEFREY
 */
public class ProductoGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form CategoriaGUI
     */
    ProductoDAO objProductoDAO = new ProductoDAO();
    ProductoTO objProductoTO = new ProductoTO();
    ButtonGroup objButtonGroup = new ButtonGroup();

    CategoriaDAO objCategoriaDAO = new CategoriaDAO();
    UnidadMedidaDAO objUnidadMedidaDAO = new UnidadMedidaDAO();

    PrePrecioDAO objPrePrecioDAO = new PrePrecioDAO();
    PrePrecioTO objPrecioTO = new PrePrecioTO();

    boolean sw;
    DefaultTableModel objDtm;
    ResultSet rsCategoria, rsProducto, rsUnidadMedida;
    int xidproducto, xidcategoria, xidunidadmedida, op, idund;
    String mensaje;

    public ProductoGUI() {
        initComponents();
        objButtonGroup.add(jradUND);
        objButtonGroup.add(jradKG);
        objButtonGroup.add(jradGL);
        objButtonGroup.add(jradRollo);
        objDtm = (DefaultTableModel) jtblRegistroProducto.getModel();
        ((DefaultTableCellRenderer) jtblRegistroProducto.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistro = new javax.swing.JPanel();
        jLabelRegistroProducto = new javax.swing.JLabel();
        jPanelDatosProducto = new javax.swing.JPanel();
        jLabelDescripcion = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jLabelDatosProducto = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtDescripcion = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();
        jtxtCantidad = new javax.swing.JTextField();
        jLabelUnidadProducto = new javax.swing.JLabel();
        jcomboxCategoria = new javax.swing.JComboBox<>();
        jLabelPrecioVenta = new javax.swing.JLabel();
        jtxtPrecioCompra = new javax.swing.JTextField();
        jLabelCategoriaProducto = new javax.swing.JLabel();
        jcomboxUnidadMedida = new javax.swing.JComboBox<>();
        jLabelPrecioCompra = new javax.swing.JLabel();
        jtxtPrecioVenta = new javax.swing.JTextField();
        jradGL = new javax.swing.JRadioButton();
        jradUND = new javax.swing.JRadioButton();
        jradKG = new javax.swing.JRadioButton();
        jLabelPrecioCompra1 = new javax.swing.JLabel();
        jradRollo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistroProducto = new javax.swing.JTable();
        jPanelBuscar = new javax.swing.JPanel();
        jLabelBuscar = new javax.swing.JLabel();
        jtxtBuscarProducto = new javax.swing.JTextField();

        jPanelRegistro.setBackground(new java.awt.Color(153, 153, 255));
        jPanelRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabelRegistroProducto.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabelRegistroProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistroProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistroProducto.setText("REGISTRO DEL PRODUCTO");
        jLabelRegistroProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelRegistroLayout = new javax.swing.GroupLayout(jPanelRegistro);
        jPanelRegistro.setLayout(jPanelRegistroLayout);
        jPanelRegistroLayout.setHorizontalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistroProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRegistroLayout.setVerticalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelRegistroProducto)
                .addGap(5, 5, 5))
        );

        jPanelDatosProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDatosProducto.setOpaque(false);

        jLabelDescripcion.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelDescripcion.setText("DESCRIPCION DEL PRODUCTO:");

        jPanelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBotones.setOpaque(false);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nuevo.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salida.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        jPanelDatos.setBackground(new java.awt.Color(153, 153, 255));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabelDatosProducto.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabelDatosProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatosProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatosProducto.setText("DATOS DEL PRODUCTO");
        jLabelDatosProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelDatosProducto)
                .addGap(5, 5, 5))
        );

        jLabelCodigo.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelCodigo.setText("CODIGO:");

        jtxtCodigo.setEditable(false);
        jtxtCodigo.setBackground(new java.awt.Color(204, 204, 204));

        jtxtDescripcion.setEditable(false);
        jtxtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtDescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDescripcionKeyTyped(evt);
            }
        });

        jLabelCantidad.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelCantidad.setText("CANTIDAD:");

        jtxtCantidad.setEditable(false);
        jtxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadActionPerformed(evt);
            }
        });
        jtxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCantidadKeyTyped(evt);
            }
        });

        jLabelUnidadProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelUnidadProducto.setText("U.MEDIDA:");

        jcomboxCategoria.setEnabled(false);
        jcomboxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboxCategoriaActionPerformed(evt);
            }
        });
        jcomboxCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcomboxCategoriaKeyReleased(evt);
            }
        });

        jLabelPrecioVenta.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelPrecioVenta.setText("PRECIO VENTA:");
        jLabelPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelPrecioVentaKeyReleased(evt);
            }
        });

        jtxtPrecioCompra.setEditable(false);
        jtxtPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrecioCompraActionPerformed(evt);
            }
        });
        jtxtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrecioCompraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPrecioCompraKeyTyped(evt);
            }
        });

        jLabelCategoriaProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelCategoriaProducto.setText("CATEGORIA:");

        jcomboxUnidadMedida.setEnabled(false);
        jcomboxUnidadMedida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcomboxUnidadMedidaMouseClicked(evt);
            }
        });
        jcomboxUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboxUnidadMedidaActionPerformed(evt);
            }
        });
        jcomboxUnidadMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcomboxUnidadMedidaKeyReleased(evt);
            }
        });

        jLabelPrecioCompra.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelPrecioCompra.setText("PRECIO COMPRA:");
        jLabelPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelPrecioCompraKeyReleased(evt);
            }
        });

        jtxtPrecioVenta.setEditable(false);
        jtxtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrecioVentaActionPerformed(evt);
            }
        });
        jtxtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrecioVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPrecioVentaKeyTyped(evt);
            }
        });

        jradGL.setText("GL");
        jradGL.setEnabled(false);
        jradGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradGLActionPerformed(evt);
            }
        });

        jradUND.setText("UND");
        jradUND.setEnabled(false);

        jradKG.setText("KG");
        jradKG.setEnabled(false);
        jradKG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradKGActionPerformed(evt);
            }
        });

        jLabelPrecioCompra1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelPrecioCompra1.setText("PRESENTACION:");
        jLabelPrecioCompra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelPrecioCompra1KeyReleased(evt);
            }
        });

        jradRollo.setText("ROLLO");
        jradRollo.setEnabled(false);
        jradRollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradRolloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosProductoLayout = new javax.swing.GroupLayout(jPanelDatosProducto);
        jPanelDatosProducto.setLayout(jPanelDatosProductoLayout);
        jPanelDatosProductoLayout.setHorizontalGroup(
            jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                        .addComponent(jLabelUnidadProducto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                        .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtDescripcion)
                            .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                                        .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosProductoLayout.createSequentialGroup()
                                        .addComponent(jLabelCategoriaProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                                        .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jcomboxUnidadMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcomboxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelDescripcion))
                        .addGap(10, 10, 10))))
            .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrecioCompra)
                    .addComponent(jtxtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecioCompra1))
                .addGap(10, 10, 10)
                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                        .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrecioVenta)
                            .addComponent(jtxtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCantidad)))
                    .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                        .addComponent(jradUND)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jradKG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jradRollo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jradGL)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDatosProductoLayout.setVerticalGroup(
            jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosProductoLayout.createSequentialGroup()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCategoriaProducto))
                .addGap(10, 10, 10)
                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUnidadProducto)
                    .addComponent(jcomboxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabelDescripcion)
                .addGap(10, 10, 10)
                .addComponent(jtxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradUND)
                    .addComponent(jradKG)
                    .addComponent(jradGL)
                    .addComponent(jLabelPrecioCompra1)
                    .addComponent(jradRollo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecioVenta)
                    .addComponent(jLabelCantidad)
                    .addComponent(jLabelPrecioCompra))
                .addGap(10, 10, 10)
                .addGroup(jPanelDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtblRegistroProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "CATEGORIA", "UDM", "DESCRIPCION", "PC", "PV", "STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblRegistroProducto.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jtblRegistroProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblRegistroProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblRegistroProducto);
        if (jtblRegistroProducto.getColumnModel().getColumnCount() > 0) {
            jtblRegistroProducto.getColumnModel().getColumn(0).setMinWidth(70);
            jtblRegistroProducto.getColumnModel().getColumn(0).setMaxWidth(70);
            jtblRegistroProducto.getColumnModel().getColumn(1).setMinWidth(120);
            jtblRegistroProducto.getColumnModel().getColumn(1).setMaxWidth(120);
            jtblRegistroProducto.getColumnModel().getColumn(2).setMinWidth(120);
            jtblRegistroProducto.getColumnModel().getColumn(2).setMaxWidth(120);
            jtblRegistroProducto.getColumnModel().getColumn(3).setMinWidth(350);
            jtblRegistroProducto.getColumnModel().getColumn(3).setMaxWidth(350);
            jtblRegistroProducto.getColumnModel().getColumn(4).setMinWidth(70);
            jtblRegistroProducto.getColumnModel().getColumn(4).setMaxWidth(70);
            jtblRegistroProducto.getColumnModel().getColumn(5).setMinWidth(70);
            jtblRegistroProducto.getColumnModel().getColumn(5).setMaxWidth(70);
            jtblRegistroProducto.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBuscar.setOpaque(false);

        jLabelBuscar.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabelBuscar.setText("BUSCAR:");

        jtxtBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBuscarProductoActionPerformed(evt);
            }
        });
        jtxtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBuscarProductoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscar)
                    .addComponent(jtxtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanelDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int op = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO QUE DESEA ELIMINAR?", "REGISTRO PRODUCTO", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (op == JOptionPane.YES_OPTION) {
                objProductoTO.setIdproducto(xidproducto);
                objProductoDAO.delete(objProductoTO);
                limpiarControles();
                JOptionPane.showMessageDialog(null, "REGISTRO ELIMINADO");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtxtBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBuscarProductoActionPerformed

    private void jtxtBuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarProductoKeyReleased
        try {
            limpiarJTable();
            if (!jtxtBuscarProducto.getText().isEmpty()) {
                rsProducto = objProductoDAO.buscar(jtxtBuscarProducto.getText().trim());
                while (rsProducto.next()) {
                    Object registro[] = {rsProducto.getInt(1), rsProducto.getString(2), rsProducto.getString(3), rsProducto.getString(4),
                        rsProducto.getDouble(5), rsProducto.getDouble(6), rsProducto.getInt(7)};
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jtxtBuscarProductoKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitarControles(true);
        limpiarControles();
        llenarComboCategoria();
        llenarComboUnidad();
        sw = true;

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (jtxtDescripcion.getText().trim().length() == 0 || jtxtPrecioCompra.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "COMPLETAR CAJA DE TEXTO", "FERRETERIA MICKY", JOptionPane.WARNING_MESSAGE);
            } else {
                obtenerIdCategoria();
                objProductoTO.setIdcategoria(xidcategoria);
                obtenerIdUnidadMedida();
                objProductoTO.setIdunidadmedida(xidunidadmedida);
                objProductoTO.setNombprod(jtxtDescripcion.getText().toUpperCase().trim());
                objProductoTO.setPcompraprod(Double.parseDouble(jtxtPrecioCompra.getText().trim()));
                objProductoTO.setPventaprod(Double.parseDouble(jtxtPrecioVenta.getText().trim()));
                objProductoTO.setCantiprod(Double.parseDouble(jtxtCantidad.getText().trim()));
                /*PREPRECIO*/
                int codproducto = objProductoDAO.obtenerCodProducto();
                int incremento = codproducto + 1;
                objPrecioTO.setIdproducto(incremento);
                objPrecioTO.setIdpresentacion(op);
                objPrecioTO.setPreprecio(Double.parseDouble(jtxtPrecioVenta.getText().trim()));
                if (sw) {
                    objProductoDAO.insert(objProductoTO);
                    objPrePrecioDAO.insert(objPrecioTO);
                    mensaje = "PRODUCTO REGISTRADO";
                } else {
                    objProductoTO.setIdproducto(Integer.parseInt(jtxtCodigo.getText()));
                    objProductoDAO.update(objProductoTO);
                    mensaje = "PRODUCTO ACTUALIZADO";
                }
                habilitarControles(false);
                JOptionPane.showMessageDialog(null, mensaje, "FERRETERIA MICKY", JOptionPane.INFORMATION_MESSAGE);
                limpiarControles();
                jcomboxCategoria.removeAllItems();
                jcomboxUnidadMedida.removeAllItems();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "FERRETERIA MICKY", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        habilitarControles(true);
        llenarComboCategoria();
        llenarComboUnidad();
        sw = false;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jtblRegistroProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRegistroProductoMouseClicked
        try {
            xidproducto = Integer.parseInt(jtblRegistroProducto.getValueAt(jtblRegistroProducto.getSelectedRow(), 0).toString());
            rsProducto.first();
            do {
                if (xidproducto == rsProducto.getInt(1)) {
                    jtxtCodigo.setText(String.valueOf(rsProducto.getInt(1)));
                    jcomboxCategoria.removeAllItems();
                    jcomboxCategoria.addItem(rsProducto.getString(2));
                    jcomboxUnidadMedida.removeAllItems();
                    jcomboxUnidadMedida.addItem(rsProducto.getString(3));
                    jtxtDescripcion.setText(rsProducto.getString(4));
                    jtxtPrecioCompra.setText(rsProducto.getString(5));
                    jtxtPrecioVenta.setText(rsProducto.getString(6));
                    jtxtCantidad.setText(rsProducto.getString(7));
                    rsProducto.last();
                }
            } while (rsProducto.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jtblRegistroProductoMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtxtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDescripcionKeyReleased

    }//GEN-LAST:event_jtxtDescripcionKeyReleased

    private void jtxtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDescripcionKeyTyped

    }//GEN-LAST:event_jtxtDescripcionKeyTyped

    private void jLabelPrecioVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelPrecioVentaKeyReleased

    }//GEN-LAST:event_jLabelPrecioVentaKeyReleased

    private void jcomboxCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboxCategoriaKeyReleased

    }//GEN-LAST:event_jcomboxCategoriaKeyReleased

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    private void jtxtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantidadKeyReleased

    }//GEN-LAST:event_jtxtCantidadKeyReleased

    private void jtxtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantidadKeyTyped

    }//GEN-LAST:event_jtxtCantidadKeyTyped

    private void jtxtPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioCompraActionPerformed

    private void jtxtPrecioCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioCompraKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioCompraKeyReleased

    private void jtxtPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioCompraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioCompraKeyTyped

    private void jcomboxUnidadMedidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboxUnidadMedidaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboxUnidadMedidaKeyReleased

    private void jcomboxUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboxUnidadMedidaActionPerformed
        jcheckSelecionar();
    }//GEN-LAST:event_jcomboxUnidadMedidaActionPerformed

    private void jLabelPrecioCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelPrecioCompraKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPrecioCompraKeyReleased

    private void jtxtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioVentaActionPerformed

    private void jtxtPrecioVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioVentaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioVentaKeyReleased

    private void jtxtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioVentaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioVentaKeyTyped

    private void jcomboxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboxCategoriaActionPerformed

    private void jradGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradGLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradGLActionPerformed

    private void jradKGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradKGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradKGActionPerformed

    private void jLabelPrecioCompra1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelPrecioCompra1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPrecioCompra1KeyReleased

    private void jradRolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradRolloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradRolloActionPerformed

    private void jcomboxUnidadMedidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcomboxUnidadMedidaMouseClicked

    }//GEN-LAST:event_jcomboxUnidadMedidaMouseClicked

    private void jtxtBuscarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBuscarProductoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCategoriaProducto;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDatosProducto;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelPrecioCompra;
    private javax.swing.JLabel jLabelPrecioCompra1;
    private javax.swing.JLabel jLabelPrecioVenta;
    private javax.swing.JLabel jLabelRegistroProducto;
    private javax.swing.JLabel jLabelUnidadProducto;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDatosProducto;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcomboxCategoria;
    private javax.swing.JComboBox<String> jcomboxUnidadMedida;
    private javax.swing.JRadioButton jradGL;
    private javax.swing.JRadioButton jradKG;
    private javax.swing.JRadioButton jradRollo;
    private javax.swing.JRadioButton jradUND;
    private javax.swing.JTable jtblRegistroProducto;
    private javax.swing.JTextField jtxtBuscarProducto;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtDescripcion;
    private javax.swing.JTextField jtxtPrecioCompra;
    private javax.swing.JTextField jtxtPrecioVenta;
    // End of variables declaration//GEN-END:variables

    private void habilitarControles(boolean b) {
        JTextField[] arrJTexFields = {jtxtDescripcion, jtxtCantidad, jtxtDescripcion,
            jtxtPrecioCompra, jtxtPrecioVenta};
        for (JTextField obJTextField : arrJTexFields) {
            obJTextField.setEditable(b);
        }
        jtxtBuscarProducto.setEditable(!b);
        jtxtDescripcion.grabFocus();
        btnGuardar.setEnabled(b);
        btnCancelar.setEnabled(b);
        btnNuevo.setEnabled(!b);
        btnEditar.setEnabled(!b);
        btnEliminar.setEnabled(!b);
        btnSalir.setEnabled(!b);
        jcomboxCategoria.setEnabled(b);
        jcomboxUnidadMedida.setEnabled(b);
    }

    private void limpiarControles() {
        limpiarJTable();
        JTextField[] objTextFields = {jtxtCodigo, jtxtBuscarProducto,
            jtxtCantidad, jtxtDescripcion, jtxtPrecioCompra, jtxtPrecioVenta};
        for (JTextField objTextField : objTextFields) {
            objTextField.setText(null);
        }
        jcomboxCategoria.removeAllItems();
        jcomboxUnidadMedida.removeAllItems();
        objButtonGroup.clearSelection();
    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }

    private void llenarComboCategoria() {
        try {
            rsCategoria = objCategoriaDAO.buscar("%");
            while (rsCategoria.next()) {
                jcomboxCategoria.addItem(rsCategoria.getString(2));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void obtenerIdCategoria() {
        try {
            String nombre = jcomboxCategoria.getSelectedItem().toString();
            rsCategoria.first();
            do {
                if (nombre.equals(rsCategoria.getString(2))) {
                    xidcategoria = rsCategoria.getInt(1);
                    rsCategoria.last();
                }
            } while (rsCategoria.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void obtenerIdUnidadMedida() {
        try {
            String nombre = jcomboxUnidadMedida.getSelectedItem().toString();
            rsUnidadMedida.first();
            do {
                if (nombre.equals(rsUnidadMedida.getString(2))) {
                    xidunidadmedida = rsUnidadMedida.getInt(1);
                    rsUnidadMedida.last();
                }
            } while (rsUnidadMedida.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void llenarComboUnidad() {
        try {
            rsUnidadMedida = objUnidadMedidaDAO.buscar("%");
            while (rsUnidadMedida.next()) {
                jcomboxUnidadMedida.addItem(rsUnidadMedida.getString(2));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    public int jcheckSelecionar() {
        try {
            String nombre = jcomboxUnidadMedida.getSelectedItem().toString();
            switch (nombre) {
                case "UNIDADES":
                    jradUND.setSelected(true);
                    op = 1;
                    break;
                case "KILOGRAMOS":
                    jradKG.setSelected(true);
                    op = 2;
                    break;
                case "ROLLO":
                    jradRollo.setSelected(true);
                    op = 3;
                    break;
                case "GALON":
                    jradGL.setSelected(true);
                    op = 4;
                    break;
            }
        } catch (Exception e) {
        }
        return op;
    }
}
