/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.ComprobantePago;

import DAO.ComprobanteDAO;
import DAO.CreditoDAO;
import DAO.DetalleComprobanteVentaDAO;
import DAO.ProductoDAO;
import DTO.ComprobanteTO;
import DTO.CreditoTO;
import DTO.DetalleComprobanteVentaTO;
import GUI.BuscarClienteComprobante;
import GUI.BuscarEncargadoComprobante;
import GUI.BuscarProductoComprobante;
import GUI.MenuGUI;
import Library.ValidarClass;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JEFREY
 */
public class ComprobanteGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ComprobanteGUI
     */
    ComprobanteDAO objComprobanteVentaDAO = new ComprobanteDAO();
    DetalleComprobanteVentaDAO objDetalleComprobanteVentaDAO = new DetalleComprobanteVentaDAO();
    ProductoDAO objProductoDAO = new ProductoDAO();
    CreditoDAO objCreditoDAO = new CreditoDAO();
    ValidarClass objValidarClass = new ValidarClass();
    JRootPane rootPane;
    boolean sw;
    DefaultTableModel objDtm;
    ResultSet rsTipoPago, rsProducto;
    int xidproducto, xidproveedor, xidcomprobante, xidtipopago;

    double precio;
    int cantidad;
    double importe;
    static double subTotal;
    static double igv;
    static double total;

    public ComprobanteGUI() {
        initComponents();
        setVisible(true);

        setSize(1047, 663);
        objDtm = (DefaultTableModel) jtblComprobante.getModel();
    }

    void generarSerie() {
        String serie = objComprobanteVentaDAO.nroSerieComprobante();
        if (serie == null) {
            jtxtSerieNumero.setText("001-1");
        } else {
            int cont = Integer.parseInt(serie);
            cont = cont + 1;
            jtxtSerieNumero.setText("001-" + cont);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jlabelcodigoProducto = new javax.swing.JLabel();
        jtxtnombreProducto = new javax.swing.JTextField();
        jlabelDescProducto = new javax.swing.JLabel();
        jtxtcodigoProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jlabelprecioCompra = new javax.swing.JLabel();
        jtxtcantidad = new javax.swing.JTextField();
        jlabelCantidad = new javax.swing.JLabel();
        jtxtPrecioProducto = new javax.swing.JTextField();
        jlabelcodigoProducto1 = new javax.swing.JLabel();
        jtxtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblComprobante = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlabelTotal = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jlabelTotal1 = new javax.swing.JLabel();
        jlabelTotal2 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtIGV = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jtxtnombreCliente = new javax.swing.JTextField();
        jlabelnombreProveedor = new javax.swing.JLabel();
        btnbuscarCliente = new javax.swing.JButton();
        jlabelnombreProveedor1 = new javax.swing.JLabel();
        jtxtcodigoCliente = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jtxtnombreEncargado = new javax.swing.JTextField();
        jlabelnombreProveedor2 = new javax.swing.JLabel();
        btnbuscarProveedor = new javax.swing.JButton();
        jlabelnombreProveedor3 = new javax.swing.JLabel();
        jtxtcodigoEncargado = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jtxtSerieNumero = new javax.swing.JTextField();
        jlabelnombreProveedor4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlabelTotal3 = new javax.swing.JLabel();
        jtxtVuelto = new javax.swing.JTextField();
        jtxtTotalPago = new javax.swing.JTextField();
        jlabelTotal4 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("COMPROBANTE DE VENTA");
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(3, 3, 3))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlabelcodigoProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelcodigoProducto.setText("CODIGO:");

        jtxtnombreProducto.setEditable(false);
        jtxtnombreProducto.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreProductoKeyTyped(evt);
            }
        });

        jlabelDescProducto.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelDescProducto.setText("DESCRIPCION PRODUCTO:");

        jtxtcodigoProducto.setEditable(false);
        jtxtcodigoProducto.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoProductoActionPerformed(evt);
            }
        });
        jtxtcodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoProductoKeyTyped(evt);
            }
        });

        btnBuscarProducto.setText("BUSCAR");
        btnBuscarProducto.setEnabled(false);
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jlabelprecioCompra.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelprecioCompra.setText("PRECIO:");

        jtxtcantidad.setEditable(false);
        jtxtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcantidadActionPerformed(evt);
            }
        });
        jtxtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcantidadKeyTyped(evt);
            }
        });

        jlabelCantidad.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelCantidad.setText("CANTIDAD:");

        jtxtPrecioProducto.setEditable(false);
        jtxtPrecioProducto.setBackground(new java.awt.Color(204, 204, 204));
        jtxtPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrecioProductoActionPerformed(evt);
            }
        });
        jtxtPrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrecioProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPrecioProductoKeyTyped(evt);
            }
        });

        jlabelcodigoProducto1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelcodigoProducto1.setText("STOCK:");

        jtxtStock.setEditable(false);
        jtxtStock.setBackground(new java.awt.Color(204, 204, 204));
        jtxtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStockActionPerformed(evt);
            }
        });
        jtxtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtStockKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtStockKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelDescProducto)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jlabelprecioCompra)
                        .addGap(21, 21, 21)
                        .addComponent(jtxtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlabelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jtxtcodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBuscarProducto))
                                .addComponent(jlabelcodigoProducto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlabelcodigoProducto1))
                            .addGap(45, 45, 45))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelcodigoProducto)
                    .addComponent(jlabelcodigoProducto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jlabelDescProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelprecioCompra)
                    .addComponent(jtxtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelCantidad)
                    .addComponent(jtxtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtblComprobante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "DESCRIPCION", "PRECIO", "CANTIDAD", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblComprobante);
        if (jtblComprobante.getColumnModel().getColumnCount() > 0) {
            jtblComprobante.getColumnModel().getColumn(0).setMinWidth(70);
            jtblComprobante.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtblComprobante.getColumnModel().getColumn(0).setMaxWidth(70);
            jtblComprobante.getColumnModel().getColumn(1).setMinWidth(300);
            jtblComprobante.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtblComprobante.getColumnModel().getColumn(1).setMaxWidth(300);
            jtblComprobante.getColumnModel().getColumn(2).setResizable(false);
            jtblComprobante.getColumnModel().getColumn(2).setPreferredWidth(70);
            jtblComprobante.getColumnModel().getColumn(3).setResizable(false);
            jtblComprobante.getColumnModel().getColumn(3).setPreferredWidth(70);
            jtblComprobante.getColumnModel().getColumn(4).setResizable(false);
            jtblComprobante.getColumnModel().getColumn(4).setPreferredWidth(70);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nuevo.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(9, 9, 9))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlabelTotal.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal.setText("TOTAL:");

        jtxtTotal.setEditable(false);
        jtxtTotal.setBackground(new java.awt.Color(255, 255, 153));
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jtxtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTotalKeyTyped(evt);
            }
        });

        jlabelTotal1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal1.setText("IGV 18%:");

        jlabelTotal2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal2.setText("SUBTOTAL:");

        jtxtSubTotal.setEditable(false);
        jtxtSubTotal.setBackground(new java.awt.Color(204, 204, 204));
        jtxtSubTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSubTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSubTotalKeyTyped(evt);
            }
        });

        jtxtIGV.setEditable(false);
        jtxtIGV.setBackground(new java.awt.Color(204, 204, 204));
        jtxtIGV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtIGVKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtIGVKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelTotal1)
                    .addComponent(jlabelTotal2))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtIGV, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelTotal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelTotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelTotal)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtxtnombreCliente.setEditable(false);
        jtxtnombreCliente.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreClienteActionPerformed(evt);
            }
        });
        jtxtnombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreClienteKeyTyped(evt);
            }
        });

        jlabelnombreProveedor.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor.setText("CODIGO:");

        btnbuscarCliente.setText("BUSCAR");
        btnbuscarCliente.setEnabled(false);
        btnbuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarClienteActionPerformed(evt);
            }
        });

        jlabelnombreProveedor1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor1.setText("DESCRIPCION CLIENTE:");

        jtxtcodigoCliente.setEditable(false);
        jtxtcodigoCliente.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelnombreProveedor1)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelnombreProveedor))
                        .addGap(12, 12, 12)
                        .addComponent(btnbuscarCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlabelnombreProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jlabelnombreProveedor1)
                .addGap(6, 6, 6)
                .addComponent(jtxtnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtxtnombreEncargado.setEditable(false);
        jtxtnombreEncargado.setBackground(new java.awt.Color(204, 204, 204));
        jtxtnombreEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreEncargadoActionPerformed(evt);
            }
        });
        jtxtnombreEncargado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnombreEncargadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtnombreEncargadoKeyTyped(evt);
            }
        });

        jlabelnombreProveedor2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor2.setText("CODIGO:");

        btnbuscarProveedor.setText("BUSCAR");
        btnbuscarProveedor.setEnabled(false);
        btnbuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarProveedorActionPerformed(evt);
            }
        });

        jlabelnombreProveedor3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor3.setText("DESCRIPCION ENCARGADO:");

        jtxtcodigoEncargado.setEditable(false);
        jtxtcodigoEncargado.setBackground(new java.awt.Color(204, 204, 204));
        jtxtcodigoEncargado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoEncargadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcodigoEncargadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcodigoEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelnombreProveedor2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbuscarProveedor))
                    .addComponent(jtxtnombreEncargado)
                    .addComponent(jlabelnombreProveedor3))
                .addGap(10, 10, 10))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jlabelnombreProveedor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcodigoEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelnombreProveedor3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtnombreEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtxtSerieNumero.setEditable(false);
        jtxtSerieNumero.setBackground(new java.awt.Color(204, 204, 204));
        jtxtSerieNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSerieNumeroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSerieNumeroKeyTyped(evt);
            }
        });

        jlabelnombreProveedor4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelnombreProveedor4.setText("SERIE NRO.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelnombreProveedor4)
                    .addComponent(jtxtSerieNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlabelnombreProveedor4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtSerieNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlabelTotal3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal3.setText("PAGO:");

        jtxtVuelto.setEditable(false);
        jtxtVuelto.setBackground(new java.awt.Color(255, 255, 153));
        jtxtVuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVueltoActionPerformed(evt);
            }
        });
        jtxtVuelto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtVueltoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtVueltoKeyTyped(evt);
            }
        });

        jtxtTotalPago.setEditable(false);
        jtxtTotalPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalPagoActionPerformed(evt);
            }
        });
        jtxtTotalPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTotalPagoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTotalPagoKeyTyped(evt);
            }
        });

        jlabelTotal4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jlabelTotal4.setText("VUELTO:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelTotal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelTotal4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelTotal4)
                    .addComponent(jtxtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnEliminarProducto.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/deleteproducto.png"))); // NOI18N
        btnEliminarProducto.setEnabled(false);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProductoKeyTyped

    private void jtxtnombreProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreProductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreProductoKeyReleased

    private void jtxtcodigoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoClienteKeyTyped

    private void jtxtcodigoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoClienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoClienteKeyReleased

    private void jtxtnombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreClienteKeyTyped

    private void jtxtnombreClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreClienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreClienteKeyReleased

    private void jtxtcodigoProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoKeyReleased

    private void jtxtcodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoProductoKeyTyped

    private void jtxtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcantidadKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            agregarProducto();
        }
    }//GEN-LAST:event_jtxtcantidadKeyReleased

    private void jtxtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcantidadKeyTyped

    }//GEN-LAST:event_jtxtcantidadKeyTyped

    private void jtxtnombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreClienteActionPerformed

    private void jtxtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalKeyReleased

    private void jtxtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            /*COMPROBANTE DE VENTA*/
            ComprobanteTO objComprobanteVentaTO = new ComprobanteTO();
            objComprobanteVentaTO.setIdencargado(Integer.parseInt(jtxtcodigoEncargado.getText()));
            objComprobanteVentaTO.setIdcliente(Integer.parseInt(jtxtcodigoCliente.getText()));
            objComprobanteVentaTO.setIdtipopago(xidtipopago);
            objComprobanteVentaTO.setNrocomp(jtxtSerieNumero.getText().trim());
            objComprobanteVentaTO.setSubTotalcomp(subTotal);
            objComprobanteVentaTO.setIgvcomp(igv);
            objComprobanteVentaTO.setTotalcomp(total);
            objComprobanteVentaDAO.insert(objComprobanteVentaTO);
            xidcomprobante = objComprobanteVentaDAO.obternerIDIngreso();
            /*DETALLE COMPROBANTE DE VENTA*/
            int filas = objDtm.getRowCount();
            for (int i = 0; i < filas; i++) {
                DetalleComprobanteVentaTO objDetalleComprobanteVentaTO = new DetalleComprobanteVentaTO();
                objDetalleComprobanteVentaTO.setIdcomprobanteVenta(xidcomprobante);
                objDetalleComprobanteVentaTO.setIdproducto(Integer.parseInt(jtblComprobante.getValueAt(i, 0).toString()));
                objDetalleComprobanteVentaTO.setPcompracomp(Double.parseDouble(jtblComprobante.getValueAt(i, 2).toString()));
                objDetalleComprobanteVentaTO.setCantidadcomp(Integer.parseInt(jtblComprobante.getValueAt(i, 3).toString()));
                objDetalleComprobanteVentaTO.setImportecomp(Double.parseDouble(jtblComprobante.getValueAt(i, 4).toString()));
                objDetalleComprobanteVentaDAO.insert(objDetalleComprobanteVentaTO);
            }
            /*CREDITO*/
            CreditoTO objCreditoTO = new CreditoTO();
            objCreditoTO.setIdcomprobante(xidcomprobante);
            objCreditoTO.setDeudacred(total);
            objCreditoDAO.insert(objCreditoTO);
            habilitarControles(false);
            JOptionPane.showMessageDialog(rootPane, "COMPROBANTE GRABADO");
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnbuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarClienteActionPerformed
        BuscarClienteComprobante objBuscarClienteGUI = new BuscarClienteComprobante();
        MenuGUI.desktopPane.add(objBuscarClienteGUI);
        objBuscarClienteGUI.setVisible(true);
        objBuscarClienteGUI.setVisible(true);
        objBuscarClienteGUI.setLocation(500, 150);
        objBuscarClienteGUI.setSize(490, 320);
        objBuscarClienteGUI.toFront();
    }//GEN-LAST:event_btnbuscarClienteActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        BuscarProductoComprobante objBuscarProductoComprobanteGUI = new BuscarProductoComprobante();
        MenuGUI.desktopPane.add(objBuscarProductoComprobanteGUI);
        objBuscarProductoComprobanteGUI.setVisible(true);
        objBuscarProductoComprobanteGUI.setLocation(500, 150);
        objBuscarProductoComprobanteGUI.setSize(595, 318);
        objBuscarProductoComprobanteGUI.toFront();
    }//GEN-LAST:event_btnBuscarProductoActionPerformed
    public void agregarProducto() {
        int stock_actual = Integer.parseInt(jtxtStock.getText());
        if (stock_actual < cantidad) {
            JOptionPane.showMessageDialog(rootPane, "STOCK INSUFICIENTE");
        } else {
            if (importe == 0) {
                JOptionPane.showMessageDialog(rootPane, "REGISTRAR LOS PRODUCTOS");
            } else {
                boolean sw = false;
                int cont = 0;
                int idproducto = Integer.parseInt(jtxtcodigoProducto.getText());
                Object registro[] = {jtxtcodigoProducto.getText(), jtxtnombreProducto.getText(), precio,
                    cantidad, importe};
                if (objDtm.getRowCount() == 0) {
                    objDtm.addRow(registro);
                    limpiarProducto();
                } else {
                    while (cont < objDtm.getRowCount()) {
                        if (idproducto == Integer.parseInt(objDtm.getValueAt(cont, 0).toString())) {
                            JOptionPane.showMessageDialog(rootPane, "REGISTRO YA EXISTE");
                            sw = true;
                        }
                        cont++;
                    }
                    if (!sw) {
                        objDtm.addRow(registro);
                    }
                }
                limpiarProducto();
            }
            calcularTotales();
        }
    }
    private void jtxtSubTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSubTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalKeyReleased

    private void jtxtSubTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSubTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalKeyTyped

    private void jtxtIGVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIGVKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIGVKeyReleased

    private void jtxtIGVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIGVKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIGVKeyTyped

    private void jtxtcodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoProductoActionPerformed

    }//GEN-LAST:event_jtxtcodigoProductoActionPerformed

    private void jtxtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcantidadActionPerformed
        precio = Double.parseDouble(jtxtPrecioProducto.getText().trim());
        cantidad = Integer.parseInt(jtxtcantidad.getText().trim());
        importe = precio * cantidad;
    }//GEN-LAST:event_jtxtcantidadActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtnombreEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoActionPerformed

    private void jtxtnombreEncargadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoKeyReleased

    private void jtxtnombreEncargadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnombreEncargadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreEncargadoKeyTyped

    private void btnbuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarProveedorActionPerformed
        BuscarEncargadoComprobante objBuscarEncargadoGUI = new BuscarEncargadoComprobante();
        MenuGUI.desktopPane.add(objBuscarEncargadoGUI);
        objBuscarEncargadoGUI.setVisible(true);
        objBuscarEncargadoGUI.setLocation(500, 150);
        objBuscarEncargadoGUI.setSize(510, 320);
        objBuscarEncargadoGUI.toFront();
    }//GEN-LAST:event_btnbuscarProveedorActionPerformed
    public void CentrarVentanaInternal(JInternalFrame objInternalFrame) {

    }
    private void jtxtcodigoEncargadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoKeyReleased

    private void jtxtcodigoEncargadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoEncargadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoEncargadoKeyTyped

    private void jtxtSerieNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSerieNumeroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSerieNumeroKeyReleased

    private void jtxtSerieNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSerieNumeroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSerieNumeroKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        generarSerie();
        habilitarControles(true);
        limpiarControles();
        sw = true;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrecioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioProductoActionPerformed

    private void jtxtPrecioProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioProductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioProductoKeyReleased

    private void jtxtPrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioProductoKeyTyped

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        objDtm.removeRow((jtblComprobante.getSelectedRow()));
        calcularTotales();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void jtxtVueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVueltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVueltoActionPerformed

    private void jtxtVueltoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtVueltoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVueltoKeyReleased

    private void jtxtVueltoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtVueltoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVueltoKeyTyped

    private void jtxtTotalPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalPagoActionPerformed
        double pago = Double.parseDouble(jtxtTotalPago.getText());
        double vuelto = pago - total;
        jtxtVuelto.setText(String.format("%.2f", vuelto));
    }//GEN-LAST:event_jtxtTotalPagoActionPerformed

    private void jtxtTotalPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalPagoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalPagoKeyReleased

    private void jtxtTotalPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTotalPagoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalPagoKeyTyped

    private void jtxtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStockActionPerformed

    private void jtxtStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtStockKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStockKeyReleased

    private void jtxtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtStockKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStockKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnbuscarCliente;
    private javax.swing.JButton btnbuscarProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelCantidad;
    private javax.swing.JLabel jlabelDescProducto;
    private javax.swing.JLabel jlabelTotal;
    private javax.swing.JLabel jlabelTotal1;
    private javax.swing.JLabel jlabelTotal2;
    private javax.swing.JLabel jlabelTotal3;
    private javax.swing.JLabel jlabelTotal4;
    private javax.swing.JLabel jlabelcodigoProducto;
    private javax.swing.JLabel jlabelcodigoProducto1;
    private javax.swing.JLabel jlabelnombreProveedor;
    private javax.swing.JLabel jlabelnombreProveedor1;
    private javax.swing.JLabel jlabelnombreProveedor2;
    private javax.swing.JLabel jlabelnombreProveedor3;
    private javax.swing.JLabel jlabelnombreProveedor4;
    private javax.swing.JLabel jlabelprecioCompra;
    private javax.swing.JTable jtblComprobante;
    private javax.swing.JTextField jtxtIGV;
    public static javax.swing.JTextField jtxtPrecioProducto;
    public static javax.swing.JTextField jtxtSerieNumero;
    public static javax.swing.JTextField jtxtStock;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTotal;
    public static javax.swing.JTextField jtxtTotalPago;
    public static javax.swing.JTextField jtxtVuelto;
    public static javax.swing.JTextField jtxtcantidad;
    public static javax.swing.JTextField jtxtcodigoCliente;
    public static javax.swing.JTextField jtxtcodigoEncargado;
    public static javax.swing.JTextField jtxtcodigoProducto;
    public static javax.swing.JTextField jtxtnombreCliente;
    public static javax.swing.JTextField jtxtnombreEncargado;
    public static javax.swing.JTextField jtxtnombreProducto;
    // End of variables declaration//GEN-END:variables

    private void habilitarControles(boolean b) {
        JTextField[] arrJTexFields = {jtxtcantidad, jtxtTotalPago};
        for (JTextField obJTextField : arrJTexFields) {
            obJTextField.setEditable(b);
        }
        btnGuardar.setEnabled(b);
        btnNuevo.setEnabled(!b);
        btnCancelar.setEnabled(b);
        btnbuscarCliente.setEnabled(b);
        btnbuscarProveedor.setEnabled(b);
        btnBuscarProducto.setEnabled(b);
        btnEliminarProducto.setEnabled(b);
    }

    private void limpiarControles() {
        limpiarJTable();
        JTextField[] objTextFields = {jtxtcodigoEncargado, jtxtnombreEncargado,
            jtxtcodigoCliente, jtxtnombreCliente, jtxtcodigoProducto,
            jtxtnombreProducto, jtxtPrecioProducto, jtxtcantidad,
            jtxtSubTotal, jtxtIGV, jtxtTotal, jtxtTotalPago, jtxtVuelto};
        for (JTextField objTextField : objTextFields) {
            objTextField.setText(null);
        }

    }

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }

    private void calcularTotales() {
        subTotal = 0;
        igv = 0;
        total = 0;
        int filas = objDtm.getRowCount();
        int cont = 0;
        while (cont < filas) {
            total = total + Double.parseDouble(objDtm.getValueAt(cont, 4).toString());
            cont++;
        }
        subTotal = total / 1.18;
        igv = total - subTotal;
        jtxtSubTotal.setText(String.format("%.2f", subTotal));
        jtxtIGV.setText(String.format("%.2f", igv));
        jtxtTotal.setText(String.format("%.2f", total));
    }

    private void limpiarProducto() {
        jtxtcodigoProducto.setText(null);
        jtxtnombreProducto.setText(null);
        jtxtPrecioProducto.setText(null);
        jtxtStock.setText(null);
        jtxtcantidad.setText(null);
        cantidad = 0;
        precio = 0;
        importe = 0;
    }
}
